<template>
 <section  class="profile q-mt-xl q-pa-sm">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <div class="privacy">
            <div class="titel">
              <img src="~assets/img/tit.png" alt="">
              <h3>{{ isEnglish ? 'Privacy Policy' : 'سياسة الخصوصيه' }}</h3>
            </div>
            <div class="Conditions"> 
              <h3 class="condH">{{ isEnglish ? 'Important note' : 'ملاحظه مهمة' }}</h3>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                    Sabri Training Center (“we,” “our,” or “us”) is committed to protecting your privacy. This Privacy Policy explains how your personal
information is collected, used, and disclosed by Sabri Training Center.
This Privacy Policy applies to our website, and its associated subdomains (collectively, our “Service”) alongside our application,
Sabri Training Center. By accessing or using our Service, you signify that you have read, understood, and agree to our collection,
storage, use, and disclosure of your personal information as described in this Privacy Policy and our Terms of Service.
                  ` 
                  : 
                  `
                  يلتزم مركز تدريب صبري ("نحن" أو "خاصتنا" أو "نحن") بحماية خصوصيتك. توضح سياسة الخصوصية هذه كيف تكون ملفات
يتم جمع المعلومات واستخدامها والإفصاح عنها من قبل مركز تدريب صبري.
تنطبق سياسة الخصوصية هذه على موقعنا الإلكتروني والمجالات الفرعية المرتبطة به (يشار إليها مجتمعة باسم "الخدمة") جنبًا إلى جنب مع تطبيقنا ،
مركز تدريب صبري. من خلال الوصول إلى خدمتنا أو استخدامها ، فإنك تشير إلى أنك قد قرأت وفهمت ووافقت على مجموعتنا ،
تخزين معلوماتك الشخصية واستخدامها والإفصاح عنها كما هو موضح في سياسة الخصوصية وشروط الخدمة الخاصة بنا. 
                  `
                }}
                

              </p>
            </div>

            <div class="uses">
              <h3 class="condH">{{ isEnglish ? `Definitions and key terms` : `التعاريف والمصطلحات الرئيسية ` }}</h3>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                    To help explain things as clearly as possible in this Privacy Policy, every time any of these terms are referenced, are strictly
defined as:
                  ` 
                  : 
                  `
                  للمساعدة في شرح الأشياء بأكبر قدر ممكن من الوضوح في سياسة الخصوصية هذه ، في كل مرة تتم الإشارة إلى أي من هذه الشروط ، يتم الإشارة إليها بشكل صارم
معرف ك: 
                  `
                }}
              </p>
              <br>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  * Cookie: small amount of data generated by a website and saved by your web browser. It is used to identify your browser,
provide analytics, remember information about you such as your language preference or login information.

                  ` 
                  : 
                  `
                  * ملف تعريف الارتباط: كمية صغيرة من البيانات يتم إنشاؤها بواسطة موقع ويب وحفظها بواسطة متصفح الويب الخاص بك. يتم استخدامه لتحديد متصفحك ،
تقديم تحليلات ، وتذكر معلومات عنك مثل اللغة المفضلة لديك أو معلومات تسجيل الدخول. 
                  `
                }}
              </p>
              <br>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                    * Company: when this policy mentions “Company,” “we,” “us,” or “our,” it refers to Sabri Training Center, Khartoum, obid khatim
st that is responsible for your information under this Privacy Policy.

                  ` 
                  : 
                  `
                  * الشركة: عندما تشير هذه السياسة إلى "الشركة" أو "نحن" أو "لنا" أو "لدينا" ، فإنها تشير إلى مركز تدريب صبري ، الخرطوم ، عبيد خاتم
st هي المسؤولة عن معلوماتك بموجب سياسة الخصوصية هذه. 
                  `
                }}
              </p>
              <br>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                    * Country: where Sabri Training Center or the owners/founders of Sabri Training Center are based, in this case is Sudan

                  ` 
                  : 
                  `
                  * الدولة: مقر مركز تدريب صبري أو مالكو / مؤسسو مركز تدريب صبري ، في هذه الحالة هي السودان 
                  `
                }}
              </p>
              <br>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                    * Customer: refers to the company, organization or person that signs up to use the Sabri Training Center Service to manage
the relationships with your consumers or service users.

                  ` 
                  : 
                  `
                  * العميل: يشير إلى الشركة أو المؤسسة أو الشخص الذي قام بالتسجيل لاستخدام خدمة مركز تدريب صبري للإدارة
العلاقات مع المستهلكين أو مستخدمي الخدمة. 
                  `
                }}
              </p>
              <br>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                    * Device: any internet connected device such as a phone, tablet, computer or any other device that can be used to visit
Sabri Training Center and use the services.

                  ` 
                  : 
                  `
                  * الجهاز: أي جهاز متصل بالإنترنت مثل الهاتف أو الجهاز اللوحي أو الكمبيوتر أو أي جهاز آخر يمكن استخدامه للزيارة
مركز تدريب صبري واستخدام الخدمات. 
                  `
                }}
              </p>
              <br>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                    * IP address: Every device connected to the Internet is assigned a number known as an Internet protocol (IP) address.
These numbers are usually assigned in geographic blocks. An IP address can often be used to identify the location from
which a device is connecting to the Internet.

                  ` 
                  : 
                  `
                  * عنوان IP: يتم تخصيص رقم يعرف بعنوان بروتوكول الإنترنت (IP) لكل جهاز متصل بالإنترنت.
عادة ما يتم تعيين هذه الأرقام في كتل جغرافية. يمكن استخدام عنوان IP غالبًا لتحديد الموقع من
أي جهاز يتصل بالإنترنت. 
                  `
                }}
              </p>
              <br>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  * Personnel: refers to those individuals who are employed by Sabri Training Center or are under contract to perform a
service on behalf of one of the parties.

                  ` 
                  : 
                  `
                  * الموظفون: يشير إلى هؤلاء الأفراد الذين تم توظيفهم من قبل مركز تدريب صبري أو المتعاقد معهم لأداء أ
خدمة نيابة عن أحد الطرفين. 
                  `
                }}
              </p>
              <br>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                    * Personal Data: any information that directly, indirectly, or in connection with other information — including a personal
identification number — allows for the identification or identifiability of a natural person.

                  ` 
                  : 
                  `
                  * البيانات الشخصية: أي معلومات ترتبط بشكل مباشر أو غير مباشر بمعلومات أخرى - بما في ذلك المعلومات الشخصية
رقم التعريف - يسمح بتحديد هوية الشخص الطبيعي أو التعرف عليه. 
                  `
                }}
              </p>
              <br>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                    * Service: refers to the service provided by Sabri Training Center as described in the relative terms (if available) and on this
platform.

                  ` 
                  : 
                  `
                  * الخدمة: تشير إلى الخدمة التي يقدمها مركز تدريب صبري كما هو موضح في المصطلحات ذات الصلة (إن وجدت) وعلى هذا
برنامج. 
                  `
                }}
              </p>
              <br>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                    * Third-party service: refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide
our content or whose products or services we think may interest you.
                  ` 
                  : 
                  `
                  * خدمة الطرف الثالث: تشير إلى المعلنين ورعاة المسابقة والشركاء الترويجيين والتسويق وغيرهم ممن يقدمونها
المحتوى الخاص بنا أو المنتجات أو الخدمات التي نعتقد أنها قد تهمك. 
                  `
                }}
              </p>
              <br>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                    * Website: Sabri Training Center’s site, which can be accessed via this URL: stc.training
                  ` 
                  : 
                  `
                  * الموقع الإلكتروني: موقع مركز تدريب صبري ، والذي يمكن الوصول إليه عبر عنوان URL التالي: stc.training 
                  `
                }}
              </p>
              <br>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  * You: a person or entity that is registered with Sabri Training Center to use the Services.
                  ` 
                  : 
                  `
                  * You: a person or entity that is registered with Sabri Training Center to use the Services.
                  `
                }}
              </p>
              <br>
            </div>
            <div class="uses">
              <h3 class="condH">{{ isEnglish ? `You: a person or entity that is registered with Sabri Training Center to use the Services.
` : `أنت: شخص أو كيان مسجل في مركز تدريب صبري لاستخدام الخدمات. ` }}</h3>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                    We collect information from you when you visit our website, register on our site, place an order, subscribe to our newsletter,
respond to a survey or fill out a form.

                  ` 
                  : 
                  `
                  نقوم بجمع معلومات منك عندما تزور موقعنا على الإنترنت ، أو تقوم بالتسجيل في موقعنا ، أو تقوم بتقديم طلب ، أو تشترك في النشرة الإخبارية لدينا ،
الرد على استطلاع أو ملء نموذج. 
                  `
                }}
              </p>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  * Name / Usernam
                  ` 
                  : 
                  `
                  * Name / Usernam
                  `
                }}
              </p>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  * Phone Numbers
                  ` 
                  : 
                  `
                  * Phone Numbers
                  `
                }}
              </p>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  * Email Addresses
                  ` 
                  : 
                  `
                  * Email Addresses
                  `
                }}
              </p>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  * Password
                  ` 
                  : 
                  `
                  * Password
                  `
                }}
              </p>
              <br>
            </div>

            <div class="uses">
              <h3 class="condH">{{ isEnglish ? `When does Sabri Training Center use end user
information from third parties?` : `متى يستخدم مركز تدريب صبري المستخدم النهائي
معلومات من أطراف ثالثة؟ ` }}</h3>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  Sabri Training Center will collect End User Data necessary to provide the Sabri Training Center services to our customers. End
users may voluntarily provide us with information they have made available on social media websites. If you provide us with any
such information, we may collect publicly available information from the social media websites you have indicated. You can
control how much of your information social media websites make public by visiting these websites and changing your privacy
settings.
                  ` 
                  : 
                  `
                  سيقوم مركز تدريب صبري بجمع بيانات المستخدم النهائي اللازمة لتقديم خدمات مركز تدريب صبري لعملائنا. نهاية
قد يزودنا المستخدمون طواعية بالمعلومات التي أتاحوها على مواقع التواصل الاجتماعي. إذا قمت بتزويدنا بأي
مثل هذه المعلومات ، قد نجمع المعلومات المتاحة للجمهور من مواقع التواصل الاجتماعي التي أشرت إليها. يمكنك
التحكم في مقدار المعلومات التي تنشرها مواقع التواصل الاجتماعي على الإنترنت من خلال زيارة هذه المواقع وتغيير خصوصيتك
الإعدادات. 
                  `
                }}
              </p>
              <br>
            </div>

            <div class="uses">
              <h3 class="condH">{{ isEnglish ? `When does Sabri Training Center use customer
information from third parties?` : `متى يستخدم مركز تدريب صبري العميل
معلومات من أطراف ثالثة؟ ` }}</h3>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  We receive some information from the third parties when you contact us. For example, when you submit your email address to
us to show interest in becoming a Sabri Training Center customer, we receive information from a third party that provides
automated fraud detection services to Sabri Training Center. We also occasionally collect information that is made publicly
available on social media websites. You can control how much of your information social media websites make public by visiting
these websites and changing your privacy settings.
                  ` 
                  : 
                  `
                  نتلقى بعض المعلومات من الأطراف الثالثة عندما تتصل بنا. على سبيل المثال ، عندما ترسل عنوان بريدك الإلكتروني إلى
لإظهار اهتمامنا بأن نصبح عملاء مركز تدريب صبري ، نتلقى معلومات من طرف ثالث يوفرها
خدمات كشف الاحتيال الآلي لمركز تدريب صبري. كما نقوم أحيانًا بجمع المعلومات التي يتم نشرها بشكل عام
متاح على مواقع التواصل الاجتماعي. يمكنك التحكم في مقدار المعلومات التي تتيحها مواقع التواصل الاجتماعي الخاصة بك للجمهور من خلال الزيارة
هذه المواقع وتغيير إعدادات الخصوصية الخاصة بك. 
                  `
                }}
              </p>
              <br>
            </div>
            <div class="uses">
              <h3 class="condH">{{ isEnglish ? `Do we share the information we collect with third
parties?` : `هل نشارك المعلومات التي نجمعها مع ثالث
حفلات؟ ` }}</h3>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  We may share the information that we collect, both personal and non-personal, with third parties such as advertisers, contest
sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may
interest you. We may also share it with our current and future affiliated companies and business partners, and if we are involved
in a merger, asset sale or other business reorganization, we may also share or transfer your personal and non-personal
information to our successors-in-interest.
                  ` 
                  : 
                  `
                  قد نشارك المعلومات التي نجمعها ، الشخصية وغير الشخصية ، مع أطراف ثالثة مثل المعلنين
الرعاة والشركاء الترويجيين والتسويق وغيرهم ممن يقدمون المحتوى الخاص بنا أو الذين نعتقد أن منتجاتهم أو خدماتهم قد تكون كذلك
اثار اهتمامك. يجوز لنا أيضًا مشاركتها مع شركاتنا التابعة الحالية والمستقبلية وشركاء الأعمال ، وإذا كنا مشاركين
في عملية الدمج أو بيع الأصول أو إعادة تنظيم الأعمال الأخرى ، يجوز لنا أيضًا مشاركة أو نقل بياناتك الشخصية وغير الشخصية
معلومات لخلفائنا في المصلحة. 
                  `
                }}
              </p>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  We may engage trusted third party service providers to perform functions and provide services to us, such as hosting and
maintaining our servers and the website, database storage and management, e-mail management, storage marketing, credit card
processing, customer service and fulfilling orders for products and services you may purchase through the website. We will
likely share your personal information, and possibly some non-personal information, with these third parties to enable them to
perform these services for us and for you.
                  ` 
                  : 
                  `
                  قد نقوم بإشراك موفري خدمات الطرف الثالث الموثوق بهم لأداء الوظائف وتقديم الخدمات لنا ، مثل الاستضافة و
صيانة خوادمنا وموقعنا على الويب ، وتخزين وإدارة قاعدة البيانات ، وإدارة البريد الإلكتروني ، وتسويق التخزين ، وبطاقات الائتمان
معالجة وخدمة العملاء وتلبية طلبات المنتجات والخدمات التي قد تشتريها من خلال الموقع الإلكتروني. سنقوم
من المحتمل أن تشارك معلوماتك الشخصية ، وربما بعض المعلومات غير الشخصية ، مع هذه الأطراف الثالثة لتمكينها من ذلك
أداء هذه الخدمات لنا ولكم. 
                  `
                }}
              </p>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  We may share portions of our log file data, including IP addresses, for analytics purposes with third parties such as web
analytics partners, application developers, and ad networks. If your IP address is shared, it may be used to estimate general
location and other technographics such as connection speed, whether you have visited the website in a shared location, and
type of the device used to visit the website. They may aggregate information about our advertising and what you see on the
website and then provide auditing, research and reporting for us and our advertisers.

                  ` 
                  : 
                  `
                  يجوز لنا مشاركة أجزاء من بيانات ملف السجل لدينا ، بما في ذلك عناوين IP ، لأغراض التحليلات مع أطراف ثالثة مثل الويب
شركاء التحليلات ومطوري التطبيقات والشبكات الإعلانية. إذا تمت مشاركة عنوان IP الخاص بك ، فيمكن استخدامه لتقدير عام
الموقع والتقنيات الأخرى مثل سرعة الاتصال ، وما إذا كنت قد زرت موقع الويب في موقع مشترك ، و
نوع الجهاز المستخدم لزيارة الموقع. قد يقومون بتجميع معلومات حول إعلاناتنا وما تراه على
موقع الويب ثم توفير التدقيق والبحث وإعداد التقارير لنا وللمعلنين لدينا. 
                  `
                }}
              </p>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  We may also disclose personal and non-personal information about you to government or law enforcement officials or private
parties as we, in our sole discretion, believe necessary or appropriate in order to respond to claims, legal process (including
subpoenas), to protect our rights and interests or those of a third party, the safety of the public or any person, to prevent or
stop any illegal, unethical, or legally actionable activity, or to otherwise comply with applicable court orders, laws, rules and
regulations.
                  ` 
                  : 
                  `
                  قد نكشف أيضًا عن معلومات شخصية وغير شخصية عنك للحكومة أو مسؤولي إنفاذ القانون أو القطاع الخاص
الأطراف كما نعتقد ، وفقًا لتقديرنا الخاص ، ضروريًا أو مناسبًا للرد على المطالبات والإجراءات القانونية (بما في ذلك
مذكرات الاستدعاء) ، لحماية حقوقنا ومصالحنا أو تلك الخاصة بطرف ثالث ، أو سلامة الجمهور أو أي شخص ، لمنع أو
وقف أي نشاط غير قانوني أو غير أخلاقي أو قابل للتنفيذ قانونيًا ، أو للامتثال لأوامر المحكمة والقوانين والقواعد المعمول بها و
أنظمة. 
                  `
                }}
              </p>
              <br>
            </div>

            <div class="uses">
              <h3 class="condH">{{ isEnglish ? `Where and when is information collected from
customers and end users?` : `أين ومتى يتم جمع المعلومات من
العملاء والمستخدمين النهائيين؟` }}</h3>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  Sabri Training Center will collect personal information that you submit to us. We may also receive personal information about
you from third parties as described above.
                  ` 
                  : 
                  `
                  سيقوم مركز تدريب صبري بجمع المعلومات الشخصية التي ترسلها إلينا. قد نتلقى أيضًا معلومات شخصية حول
أنت من جهات خارجية كما هو موضح أعلاه. 
                  `
                }}
              </p>
              <br>
            </div>

            <div class="uses">
              <h3 class="condH">{{ isEnglish ? `How Do We Use The Information We Collect?` : `كيف نستخدم المعلومات التي نجمعها؟ ` }}</h3>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  Any of the information we collect from you may be used in one of the following ways:

                  ` 
                  : 
                  `
                  يمكن استخدام أي من المعلومات التي نجمعها منك بإحدى الطرق التالية:
                  `
                }}
              </p>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  * To personalize your experience (your information helps us to better respond to your individual needs)
                  ` 
                  :
                  `
                  * لتخصيص تجربتك (تساعدنا معلوماتك على الاستجابة بشكل أفضل لاحتياجاتك الفردية) 
                  `
                }}
              </p>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  * To improve our website (we continually strive to improve our website offerings based on the information and feedback
we receive from you)

                  ` 
                  : 
                  `
                  * لتحسين موقعنا (نحن نسعى باستمرار لتحسين عروض موقعنا بناءً على المعلومات والتعليقات
نتلقاها منك)
                  `
                }}
              </p>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  * To improve customer service (your information helps us to more effectively respond to your customer service requests
and support needs)

                  ` 
                  : 
                  `
                  * لتحسين خدمة العملاء (تساعدنا معلوماتك على الاستجابة بشكل أكثر فعالية لطلبات خدمة العملاء الخاصة بك
واحتياجات الدعم) 
                  `
                }}
              </p>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  * To process transactions
                  ` 
                  : 
                  `
                  * لمعالجة المعاملات 
                  `
                }}
              </p>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  * To administer a contest, promotion, survey or other site feature
                  ` 
                  : 
                  `
                  * لإدارة مسابقة أو ترويج أو استطلاع أو ميزة أخرى في الموقع
                  `
                }}
              </p>
              <br>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  * To send periodic emails
                  ` 
                  : 
                  `
                  * لإرسال رسائل بريد إلكتروني دورية
                  `
                }}
              </p>
              <br>
            </div>

            <div class="uses">
              <h3 class="condH">{{ isEnglish ? 'How Do We Use Your Email Address?' : 'كيف نستخدم عنوان بريدك الإلكتروني؟' }}</h3>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  By submitting your email address on this website, you agree to receive emails from us. You can cancel your participation in any
of these email lists at any time by clicking on the opt-out link or other unsubscribe option that is included in the respective
email. We only send emails to people who have authorized us to contact them, either directly, or through a third party. We do
not send unsolicited commercial emails, because we hate spam as much as you do. By submitting your email address, you also
agree to allow us to use your email address for customer audience targeting on sites like Facebook, where we display custom
advertising to specific people who have opted-in to receive communications from us. Email addresses submitted only through
the order processing page will be used for the sole purpose of sending you information and updates pertaining to your order. If,
however, you have provided the same email to us through another method, we may use it for any of the purposes stated in this
Policy. Note: If at any time you would like to unsubscribe from receiving future emails, we include detailed unsubscribe
instructions at the bottom of each email.
                  ` 
                  : 
                  `
                    بإرسال عنوان بريدك الإلكتروني على هذا الموقع ، فإنك توافق على تلقي رسائل بريد إلكتروني منا. يمكنك إلغاء مشاركتك في أي
قوائم البريد الإلكتروني هذه في أي وقت عن طريق النقر فوق ارتباط إلغاء الاشتراك أو خيار إلغاء الاشتراك الآخر المضمن في كل منها
البريد الإلكتروني. نحن نرسل رسائل البريد الإلكتروني فقط إلى الأشخاص الذين سمحوا لنا بالاتصال بهم ، إما بشكل مباشر أو من خلال طرف ثالث. نحن نفعل
عدم إرسال رسائل بريد إلكتروني تجارية غير مرغوب فيها ، لأننا نكره البريد العشوائي مثلك تمامًا. من خلال تقديم عنوان البريد الإلكتروني الخاص بك ، أنت أيضًا
توافق على السماح لنا باستخدام عنوان بريدك الإلكتروني لاستهداف جمهور العملاء على مواقع مثل Facebook ، حيث نعرض مخصصًا
الإعلان لأشخاص محددين اختاروا الاشتراك لتلقي الاتصالات منا. إرسال عناوين البريد الإلكتروني فقط من خلال
سيتم استخدام صفحة معالجة الطلب لغرض وحيد هو إرسال المعلومات والتحديثات المتعلقة بطلبك. إذا،
ومع ذلك ، فقد قدمت لنا نفس البريد الإلكتروني من خلال طريقة أخرى ، وقد نستخدمه لأي من الأغراض المذكورة في هذا
سياسة. ملاحظة: إذا كنت ترغب في أي وقت في إلغاء الاشتراك من تلقي رسائل البريد الإلكتروني المستقبلية ، فإننا نقوم بتضمين إلغاء الاشتراك المفصل
التعليمات الموجودة في الجزء السفلي من كل بريد إلكتروني.
                  `
                }}
              </p>
            </div>
            <div class="uses">
              <h3 class="condH">{{ isEnglish ? 'How Long Do We Keep Your Information?' : 'كم من الوقت نحتفظ بمعلوماتك؟' }}</h3>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  We keep your information only so long as we need it to provide Sabri Training Center to you and fulfill the purposes described in
this policy. This is also the case for anyone that we share your information with and who carries out services on our behalf. When
we no longer need to use your information and there is no need for us to keep it to comply with our legal or regulatory
obligations, we’ll either remove it from our systems or depersonalize it so that we can't identify you.

                  ` 
                  : 
                  `
                  نحتفظ بمعلوماتك فقط طالما أننا بحاجة إليها لتوفير مركز تدريب صبري لك وتحقيق الأغراض الموضحة في
هذه السياسة. هذا هو الحال أيضًا بالنسبة لأي شخص نشارك معلوماتك معه ويقوم بتنفيذ الخدمات نيابة عنا. متي
لم نعد بحاجة إلى استخدام معلوماتك وليست هناك حاجة لنا للاحتفاظ بها للامتثال لقواعدنا القانونية أو التنظيمية
الالتزامات ، سنقوم إما بإزالتها من أنظمتنا أو إلغاء طابعها الشخصي حتى لا نتمكن من التعرف عليك. 
                  `
                }}
              </p>
            </div>

            <div class="uses">
              <h3 class="condH">{{ isEnglish ? 'How Do We Protect Your Information?' : 'كيف نحمي معلوماتك؟' }}</h3>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  We implement a variety of security measures to maintain the safety of your personal information when you place an order or
enter, submit, or access your personal information. We offer the use of a secure server. All supplied sensitive/credit information
is transmitted via Secure Socket Layer (SSL) technology and then encrypted into our Payment gateway providers database
only to be accessible by those authorized with special access rights to such systems, and are required to keep the information
confidential. After a transaction, your private information (credit cards, social security numbers, financials, etc.) is never kept on
file. We cannot, however, ensure or warrant the absolute security of any information you transmit to Sabri Training Center or
guarantee that your information on the Service may not be accessed, disclosed, altered, or destroyed by a breach of any of our
physical, technical, or managerial safeguards.
                  ` 
                  : 
                  `
                  We implement a variety of security measures to maintain the safety of your personal information when you place an order or
enter, submit, or access your personal information. We offer the use of a secure server. All supplied sensitive/credit information
is transmitted via Secure Socket Layer (SSL) technology and then encrypted into our Payment gateway providers database
only to be accessible by those authorized with special access rights to such systems, and are required to keep the information
confidential. After a transaction, your private information (credit cards, social security numbers, financials, etc.) is never kept on
file. We cannot, however, ensure or warrant the absolute security of any information you transmit to Sabri Training Center or
guarantee that your information on the Service may not be accessed, disclosed, altered, or destroyed by a breach of any of our
physical, technical, or managerial safeguards
                  `
                }}
              </p>
            </div>

            <div class="uses">
              <h3 class="condH">{{ isEnglish ? 'Could my information be transferred to other countries?' : `هل يمكن نقل معلوماتي إلى أخرى
الدول؟ ` }}</h3>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  Sabri Training Center is incorporated in Sudan. Information collected via our website, through direct interactions with you, or
from use of our help services may be transferred from time to time to our offices or personnel, or to third parties, located
throughout the world, and may be viewed and hosted anywhere in the world, including countries that may not have laws of
general applicability regulating the use and transfer of such data. To the fullest extent allowed by applicable law, by using any
of the above, you voluntarily consent to the trans-border transfer and hosting of such information.
                  ` 
                  : 
                  `
                  تأسيس مركز صبري للتدريب في السودان. المعلومات التي يتم جمعها عبر موقعنا الإلكتروني ، من خلال التفاعلات المباشرة معك ، أو
من استخدام خدمات المساعدة الخاصة بنا قد يتم نقلها من وقت لآخر إلى مكاتبنا أو موظفينا أو إلى جهات خارجية موجودة
في جميع أنحاء العالم ، ويمكن عرضها واستضافتها في أي مكان في العالم ، بما في ذلك البلدان التي قد لا يكون لديها قوانين
تطبيق عام ينظم استخدام ونقل مثل هذه البيانات. إلى أقصى حد يسمح به القانون المعمول به ، باستخدام أي
مما ورد أعلاه ، فإنك توافق طواعية على نقل واستضافة هذه المعلومات عبر الحدود. 
                  `
                }}
              </p>
            </div>

            <div class="uses">
              <h3 class="condH">{{ isEnglish ? `Is the information collected through the Sabri Training
Center Service secure?` : `هي المعلومات التي يتم جمعها من خلال تدريب صبري
خدمة المركز آمنة؟ ` }}</h3>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  We take precautions to protect the security of your information. We have physical, electronic, and managerial procedures to
help safeguard, prevent unauthorized access, maintain data security, and correctly use your information. However, neither
people nor security systems are foolproof, including encryption systems. In addition, people can commit intentional crimes,
make mistakes or fail to follow policies. Therefore, while we use reasonable efforts to protect your personal information, we
cannot guarantee its absolute security. If applicable law imposes any non-disclaimable duty to protect your personal
information, you agree that intentional misconduct will be the standards used to measure our compliance with that duty.

                  ` 
                  : 
                  `
                  نتخذ الاحتياطات اللازمة لحماية أمن معلوماتك. لدينا إجراءات مادية وإلكترونية وإدارية لـ
المساعدة في حماية ومنع الوصول غير المصرح به والحفاظ على أمان البيانات واستخدام معلوماتك بشكل صحيح. ومع ذلك ، لا
الأشخاص ولا أنظمة الأمان مضمونة ، بما في ذلك أنظمة التشفير. بالإضافة إلى ذلك ، يمكن للناس ارتكاب جرائم متعمدة ،
يخطئ أو يفشل في اتباع السياسات. لذلك ، بينما نبذل جهودًا معقولة لحماية معلوماتك الشخصية ، فإننا
لا يمكن أن تضمن أمنها المطلق. إذا كان القانون المعمول به يفرض أي واجب غير قابل لإخلاء المسؤولية لحماية شخصيتك
المعلومات ، أنت توافق على أن سوء السلوك المتعمد سيكون هو المعايير المستخدمة لقياس امتثالنا لهذا الواجب.
                  `
                }}
              </p>
            </div>

            <div class="uses">
              <h3 class="condH">{{ isEnglish ? `Can I update or correct my information?` : `هل يمكنني تحديث أو تصحيح معلوماتي؟` }}</h3>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  The rights you have to request updates or corrections to the information Sabri Training Center collects depend on your
relationship with Sabri Training Center. Personnel may update or correct their information as detailed in our internal company
employment policies.

                  ` 
                  : 
                  `
                  تعتمد الحقوق التي تتمتع بها في طلب التحديثات أو التصحيحات على المعلومات التي يجمعها مركز تدريب صبري على
العلاقة مع مركز تدريب صبري. قد يقوم الموظفون بتحديث أو تصحيح معلوماتهم كما هو مفصل في شركتنا الداخلية
سياسات التوظيف. 
                  `
                }}
              </p>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  Customers have the right to request the restriction of certain uses and disclosures of personally identifiable information as
follows. You can contact us in order to (1) update or correct your personally identifiable information, (2) change your
preferences with respect to communications and other information you receive from us, or (3) delete the personally identifiable
information maintained about you on our systems (subject to the following paragraph), by cancelling your account. Such
updates, corrections, changes and deletions will have no effect on other information that we maintain, or information that we
have provided to third parties in accordance with this Privacy Policy prior to such update, correction, change or deletion. To
protect your privacy and security, we may take reasonable steps (such as requesting a unique password) to verify your identity
before granting you profile access or making corrections. You are responsible for maintaining the secrecy of your unique
password and account information at all times.
                  ` 
                  : 
                  `
                  يحق للعملاء طلب تقييد استخدامات معينة والإفصاح عن معلومات التعريف الشخصية
يتبع. يمكنك الاتصال بنا من أجل (1) تحديث أو تصحيح معلومات التعريف الشخصية الخاصة بك ، (2) تغيير
التفضيلات فيما يتعلق بالاتصالات والمعلومات الأخرى التي تتلقاها منا ، أو (3) حذف معلومات التعريف الشخصية
المعلومات المحفوظة عنك على أنظمتنا (وفقًا للفقرة التالية) ، عن طريق إلغاء حسابك. مثل
لن يكون للتحديثات والتصحيحات والتغييرات والحذف أي تأثير على المعلومات الأخرى التي نحتفظ بها أو المعلومات التي نمتلكها
قدمت إلى أطراف ثالثة وفقًا لسياسة الخصوصية هذه قبل هذا التحديث أو التصحيح أو التغيير أو الحذف. ل
لحماية خصوصيتك وأمانك ، قد نتخذ خطوات معقولة (مثل طلب كلمة مرور فريدة) للتحقق من هويتك
قبل منحك حق الوصول إلى ملف التعريف أو إجراء التصحيحات. أنت مسؤول عن الحفاظ على السرية الفريدة الخاصة بك
كلمة المرور ومعلومات الحساب في جميع الأوقات.
                  `
                }}
              </p>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  You should be aware that it is not technologically possible to remove each and every record of the information you have
provided to us from our system. The need to back up our systems to protect information from inadvertent loss means that a
copy of your information may exist in a non-erasable form that will be difficult or impossible for us to locate. Promptly after
receiving your request, all personal information stored in databases we actively use, and other readily searchable media will be
updated, corrected, changed or deleted, as appropriate, as soon as and to the extent reasonably and technically practicable.

                  ` 
                  : 
                  `
                  يجب أن تدرك أنه ليس من الممكن تقنيًا إزالة كل سجل من المعلومات التي لديك
المقدمة لنا من نظامنا. الحاجة إلى نسخ أنظمتنا احتياطيًا لحماية المعلومات من الضياع غير المقصود تعني أن أ
قد توجد نسخة من معلوماتك في شكل غير قابل للمسح يصعب أو يستحيل علينا تحديد موقعه. على الفور بعد
تلقي طلبك ، ستكون جميع المعلومات الشخصية المخزنة في قواعد البيانات التي نستخدمها بنشاط ، والوسائط الأخرى القابلة للبحث بسهولة
تحديثها أو تصحيحها أو تغييرها أو حذفها ، حسب الاقتضاء ، في أقرب وقت وإلى الحد المعقول والعملي عمليًا. 
                  `
                }}
              </p>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  If you are an end user and wish to update, delete, or receive any information we have about you, you may do so by contacting
the organization of which you are a customer.

                  ` 
                  : 
                  `
                  `
                }}
              </p>
            </div>

            <div class="uses">
              <h3 class="condH">{{ isEnglish ? 'Personnel' : 'شؤون الموظفين' }}</h3>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  If you are a Sabri Training Center worker or applicant, we collect information you voluntarily provide to us. We use the
information collected for Human Resources purposes in order to administer benefits to workers and screen applicants.

                  ` 
                  : 
                  `
                  إذا كنت موظفًا أو متقدمًا في مركز تدريب صبري ، فإننا نجمع المعلومات التي تقدمها لنا طواعية. نحن نستخدم ال
المعلومات التي تم جمعها لأغراض الموارد البشرية من أجل إدارة المزايا للعمال وفحص المتقدمين. 
                  `
                }}
              </p>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  You may contact us in order to (1) update or correct your information, (2) change your preferences with respect to
communications and other information you receive from us, or (3) receive a record of the information we have relating to you.
Such updates, corrections, changes and deletions will have no effect on other information that we maintain, or information that
we have provided to third parties in accordance with this Privacy Policy prior to such update, correction, change or deletion.

                  ` 
                  : 
                  `
                  يمكنك الاتصال بنا من أجل (1) تحديث أو تصحيح معلوماتك ، (2) تغيير تفضيلاتك فيما يتعلق بـ
الاتصالات والمعلومات الأخرى التي تتلقاها منا ، أو (3) تلقي سجل بالمعلومات التي لدينا المتعلقة بك.
لن يكون لهذه التحديثات والتصحيحات والتغييرات والحذف أي تأثير على المعلومات الأخرى التي نحتفظ بها أو المعلومات التي
قدمنا لأطراف ثالثة وفقًا لسياسة الخصوصية هذه قبل هذا التحديث أو التصحيح أو التغيير أو الحذف. 
                  `
                }}
              </p>
            </div>

            <div class="uses">
              <h3 class="condH">{{ isEnglish ? 'Sale of Business' : 'بيع الأعمال ' }}</h3>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  We reserve the right to transfer information to a third party in the event of a sale, merger or other transfer of all or substantially
all of the assets of Sabri Training Center or any of its Corporate Affiliates (as defined herein), or that portion of Sabri Training
Center or any of its Corporate Affiliates to which the Service relates, or in the event that we discontinue our business or file a
petition or have filed against us a petition in bankruptcy, reorganization or similar proceeding, provided that the third party
agrees to adhere to the terms of this Privacy Policy.

                  ` 
                  : 
                  `
                  نحتفظ بالحق في نقل المعلومات إلى طرف ثالث في حالة البيع أو الدمج أو النقل الآخر للكل أو بشكل جوهري
جميع أصول مركز تدريب Sabri أو أي من الشركات التابعة له (كما هو محدد هنا) ، أو ذلك الجزء من تدريب Sabri
المركز أو أي من الشركات التابعة له التي تتعلق بها الخدمة ، أو في حالة توقفنا عن عملنا أو تقديم ملف
التماسًا أو رفع التماسًا ضدنا في قضية إفلاس أو إعادة تنظيم أو إجراء مشابه ، بشرط أن يكون الطرف الثالث
يوافق على الالتزام بشروط سياسة الخصوصية هذه. 
                  `
                }}
              </p>
            </div>
            <div class="uses">
              <h3 class="condH">{{ isEnglish ? 'Affiliates' : 'الشركات التابعة' }}</h3>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  We may disclose information (including personal information) about you to our Corporate Affiliates. For purposes of this Privacy
Policy, "Corporate Affiliate" means any person or entity which directly or indirectly controls, is controlled by or is under common
control with Sabri Training Center, whether by ownership or otherwise. Any information relating to you that we provide to our
Corporate Affiliates will be treated by those Corporate Affiliates in accordance with the terms of this Privacy Policy.
                  ` 
                  : 
                  `
                  قد نكشف عن معلومات (بما في ذلك المعلومات الشخصية) عنك إلى الشركات التابعة لنا. لأغراض هذه الخصوصية
السياسة ، "الشركة التابعة للشركة" تعني أي شخص أو كيان يتحكم بشكل مباشر أو غير مباشر أو يخضع لسيطرة مشتركة
السيطرة مع مركز تدريب صبري سواء عن طريق الملكية أو غير ذلك. أي معلومات تتعلق بك نقدمها لنا
سيتم التعامل مع الشركات التابعة من قبل تلك الشركات التابعة وفقًا لشروط سياسة الخصوصية هذه. 
                  `
                }}
              </p>
            </div>
            <div class="uses">
              <h3 class="condH">{{ isEnglish ? 'Governing Law' : 'القانون الذي يحكم' }}</h3>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  This Privacy Policy is governed by the laws of Sudan without regard to its conflict of laws provision. You consent to the
exclusive jurisdiction of the courts in connection with any action or dispute arising between the parties under or in connection
with this Privacy Policy except for those individuals who may have rights to make claims under Privacy Shield, or the Swiss-US
framework.

                  ` 
                  : 
                  `
                  تخضع سياسة الخصوصية هذه لقوانين السودان بغض النظر عن تعارضها مع أحكام القوانين. أنت توافق على
الاختصاص الحصري للمحاكم فيما يتعلق بأي إجراء أو نزاع ينشأ بين الأطراف بموجب أو فيما يتعلق
مع سياسة الخصوصية هذه باستثناء الأفراد الذين قد يكون لديهم حقوق لتقديم مطالبات بموجب Privacy Shield ، أو Swiss-US
إطار العمل. 
                  `
                }}
              </p>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  The laws of Sudan, excluding its conflicts of law rules, shall govern this Agreement and your use of the website. Your use of the
website may also be subject to other local, state, national, or international laws.

                  ` 
                  : 
                  `
                  تحكم قوانين السودان ، باستثناء تعارضها مع قواعد القانون ، هذه الاتفاقية واستخدامك للموقع. استخدامك لملف
قد يخضع موقع الويب أيضًا لقوانين محلية أو وطنية أو وطنية أو دولية أخرى. 
                  `
                }}
              </p>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  By using Sabri Training Center or contacting us directly, you signify your acceptance of this Privacy Policy. If you do not agree
to this Privacy Policy, you should not engage with our website, or use our services. Continued use of the website, direct
engagement with us, or following the posting of changes to this Privacy Policy that do not significantly affect the use or
disclosure of your personal information will mean that you accept those changes.
                  ` 
                  : 
                  `
                  باستخدام مركز تدريب صبري أو الاتصال بنا مباشرة ، فإنك تشير إلى موافقتك على سياسة الخصوصية هذه. إذا كنت لا توافق
وفقًا لسياسة الخصوصية هذه ، يجب ألا تتعامل مع موقعنا الإلكتروني أو تستخدم خدماتنا. استمرار استخدام الموقع بشكل مباشر
التعامل معنا ، أو متابعة نشر التغييرات على سياسة الخصوصية هذه التي لا تؤثر بشكل كبير على الاستخدام أو
الكشف عن معلوماتك الشخصية يعني أنك تقبل هذه التغييرات. 
                  `
                }}
              </p>
            </div>

            <div class="uses">
              <h3 class="condH">{{ isEnglish ? 'Your Consent' : 'موافقتك' }}</h3>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  We've updated our Privacy Policy to provide you with complete transparency into what is being set when you visit our site and
how it's being used. By using our Sabri Training Center, registering an account, or making a purchase, you hereby consent to our
Privacy Policy and agree to its terms.

                  ` 
                  : 
                  `
                  لقد قمنا بتحديث سياسة الخصوصية الخاصة بنا لتزويدك بشفافية كاملة فيما يتعلق بما يتم تعيينه عند زيارة موقعنا و
كيف يتم استخدامه. باستخدام مركز تدريب صبري الخاص بنا أو تسجيل حساب أو إجراء عملية شراء ، فأنت بذلك توافق على
سياسة الخصوصية والموافقة على شروطها. 
                  `
                }}
              </p>
            </div>
            <div class="uses">
              <h3 class="condH">{{ isEnglish ? `Links to Other Websites
` : `روابط لمواقع أخرى ` }}</h3>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  This Privacy Policy applies only to the Services. The Services may contain links to other websites not operated or controlled
by Sabri Training Center. We are not responsible for the content, accuracy or opinions expressed in such websites, and such
websites are not investigated, monitored or checked for accuracy or completeness by us. Please remember that when you use
a link to go from the Services to another website, our Privacy Policy is no longer in effect. Your browsing and interaction on any
other website, including those that have a link on our platform, is subject to that website’s own rules and policies. Such third
parties may use their own cookies or other methods to collect information about you.

                  ` 
                  : 
                  `
                  تنطبق سياسة الخصوصية هذه على الخدمات فقط. قد تحتوي الخدمات على روابط لمواقع أخرى لا يتم تشغيلها أو التحكم فيها
بواسطة مركز تدريب صبري. نحن لسنا مسؤولين عن المحتوى أو الدقة أو الآراء المعبر عنها في مثل هذه المواقع ، وما إلى ذلك
لا يتم التحقيق في مواقع الويب أو مراقبتها أو التحقق من دقتها أو اكتمالها من قبلنا. يرجى تذكر ذلك عند استخدام
رابط للانتقال من الخدمات إلى موقع ويب آخر ، لم تعد سياسة الخصوصية الخاصة بنا سارية المفعول. التصفح والتفاعل على أي
يخضع موقع الويب الآخر ، بما في ذلك المواقع التي تحتوي على رابط على نظامنا الأساسي ، لقواعد وسياسات موقع الويب هذا. هذا الثالث
قد تستخدم الأطراف ملفات تعريف الارتباط الخاصة بهم أو طرق أخرى لجمع معلومات عنك. 
                  `
                }}
              </p>
            </div>

            <div class="uses">
              <h3 class="condH">{{ isEnglish ? 'Cookies' : 'Cookies' }}</h3>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  Sabri Training Center uses "Cookies" to identify the areas of our website that you have visited. A Cookie is a small piece of data
stored on your computer or mobile device by your web browser. We use Cookies to enhance the performance and functionality
of our website but are non-essential to their use. However, without these cookies, certain functionality like videos may become
unavailable or you would be required to enter your login details every time you visit the website as we would not be able to
remember that you had logged in previously. Most web browsers can be set to disable the use of Cookies. However, if you
disable Cookies, you may not be able to access functionality on our website correctly or at all. We never place Personally
Identifiable Information in Cookies.

                  ` 
                  :
                  `
                  يستخدم مركز تدريب صبري "ملفات تعريف الارتباط" لتحديد مناطق موقعنا التي قمت بزيارتها. ملف تعريف الارتباط هو جزء صغير من البيانات
المخزنة على جهاز الكمبيوتر أو الجهاز المحمول بواسطة متصفح الويب الخاص بك. نستخدم ملفات تعريف الارتباط لتحسين الأداء والوظائف
من موقعنا ولكنها غير ضرورية لاستخدامها. ومع ذلك ، بدون ملفات تعريف الارتباط هذه ، قد تصبح وظائف معينة مثل مقاطع الفيديو
غير متاح أو ستتم مطالبتك بإدخال تفاصيل تسجيل الدخول الخاصة بك في كل مرة تزور فيها موقع الويب حيث لن نتمكن من ذلك
تذكر أنك قمت بتسجيل الدخول مسبقًا. يمكن ضبط معظم متصفحات الويب لتعطيل استخدام ملفات تعريف الارتباط. ومع ذلك ، إذا كنت
تعطيل ملفات تعريف الارتباط ، قد لا تتمكن من الوصول إلى الوظائف على موقعنا بشكل صحيح أو على الإطلاق. نحن لا نضع شخصيا أبدا
معلومات تحديد الهوية في ملفات تعريف الارتباط. 
                  `
                }}
              </p>
            </div>
            <div class="uses">
              <h3 class="condH">{{ isEnglish ? `Blocking and disabling cookies and similar
technologies` : `حظر وتعطيل ملفات تعريف الارتباط وما شابه ذلك
التقنيات ` }}</h3>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  Wherever you're located you may also set your browser to block cookies and similar technologies, but this action may block our
essential cookies and prevent our website from functioning properly, and you may not be able to fully utilize all of its features
and services. You should also be aware that you may also lose some saved information (e.g. saved login details, site
preferences) if you block cookies on your browser. Different browsers make different controls available to you. Disabling a
cookie or category of cookie does not delete the cookie from your browser, you will need to do this yourself from within your
browser, you should visit your browser's help menu for more information.
                  ` 
                  : 
                  `
                  أينما كنت ، يمكنك أيضًا ضبط متصفحك لحظر ملفات تعريف الارتباط والتقنيات المماثلة ، ولكن هذا الإجراء قد يحظر ملفات
ملفات تعريف الارتباط الأساسية وتمنع موقع الويب الخاص بنا من العمل بشكل صحيح ، وقد لا تتمكن من الاستفادة الكاملة من جميع ميزاته
والخدمات. يجب أن تدرك أيضًا أنك قد تفقد أيضًا بعض المعلومات المحفوظة (مثل تفاصيل تسجيل الدخول المحفوظة والموقع
التفضيلات) إذا قمت بحظر ملفات تعريف الارتباط على متصفحك. تتيح لك المتصفحات المختلفة عناصر تحكم مختلفة. تعطيل أ
لا يحذف ملف تعريف الارتباط أو فئة ملفات تعريف الارتباط ملف تعريف الارتباط من متصفحك ، ستحتاج إلى القيام بذلك بنفسك من داخل ملف
المتصفح ، يجب عليك زيارة قائمة تعليمات المستعرض الخاص بك للحصول على مزيد من المعلومات. 
                  `
                }}
              </p>
            </div>

            <div class="uses">
              <h3 class="condH">{{ isEnglish ? 'Payment Details' : 'بيانات الدفع' }}</h3>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  In respect to any credit card or other payment processing details you have provided us, we commit that this confidential
information will be stored in the most secure manner possible.

                  ` 
                  : 
                  `
                  فيما يتعلق بأي بطاقة ائتمان أو تفاصيل معالجة الدفع الأخرى التي قدمتها لنا ، فإننا نلتزم بهذه السرية
سيتم تخزين المعلومات بأكثر الطرق أمانًا قدر الإمكان. 
                  `
                }}
              </p>
            </div>

            <div class="uses">
              <h3 class="condH">{{ isEnglish ? `Kids' Privacy` : `خصوصية الأطفال` }}</h3>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  We collect information from kids under the age of 13 just to better our services. If You are a parent or guardian and You are
aware that Your child has provided Us with Personal Data without your permission, please contact Us. If We become aware that
We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to
remove that information from Our servers.
                  ` 
                  : 
                  `
                  نقوم بجمع المعلومات من الأطفال دون سن 13 عامًا فقط لتحسين خدماتنا. إذا كنت والدًا أو وصيًا وأنت كذلك
مدركًا أن طفلك قد زودنا ببيانات شخصية دون إذنك ، يرجى الاتصال بنا. إذا علمنا ذلك
لقد جمعنا بيانات شخصية من أي شخص يقل عمره عن 13 عامًا دون التحقق من موافقة الوالدين ، ونتخذ الخطوات اللازمة لذلك
إزالة هذه المعلومات من خوادمنا. 
                  `
                }}
              </p>
            </div>

            <div class="uses">
              <h3 class="condH">{{ isEnglish ? `Changes To Our Privacy Policy
` : `التغييرات على سياسة الخصوصية الخاصة بنا` }}</h3>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  We may change our Service and policies, and we may need to make changes to this Privacy Policy so that they accurately
reflect our Service and policies. Unless otherwise required by law, we will notify you (for example, through our Service) before
we make changes to this Privacy Policy and give you an opportunity to review them before they go into effect. Then, if you
continue to use the Service, you will be bound by the updated Privacy Policy. If you do not want to agree to this or any updated
Privacy Policy, you can delete your account.
                  ` 
                  : 
                  `
                  قد نقوم بتغيير خدمتنا وسياساتنا ، وقد نحتاج إلى إجراء تغييرات على سياسة الخصوصية هذه حتى تكون دقيقة
تعكس خدماتنا وسياساتنا. ما لم يقتض القانون خلاف ذلك ، سنخطرك (على سبيل المثال ، من خلال خدمتنا) من قبل
نجري تغييرات على سياسة الخصوصية هذه ونمنحك فرصة لمراجعتها قبل دخولها حيز التنفيذ. ثم إذا كنت
الاستمرار في استخدام الخدمة ، سوف تكون ملزمًا بسياسة الخصوصية المحدثة. إذا كنت لا تريد الموافقة على هذا أو أي تحديث
سياسة الخصوصية ، يمكنك حذف حسابك. 
                  `
                }}
              </p>
            </div>

            <div class="uses">
              <h3 class="condH">{{ isEnglish ? 'Third-Party Services' : 'خدمات الطرف الثالث ' }}</h3>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  We may display, include or make available third-party content (including data, information, applications and other products
services) or provide links to third-party websites or services ("Third- Party Services").
                  ` 
                  : 
                  `
                  يجوز لنا عرض محتوى جهة خارجية أو تضمينه أو توفيره (بما في ذلك البيانات والمعلومات والتطبيقات والمنتجات الأخرى
الخدمات) أو توفير روابط لمواقع أو خدمات الجهات الخارجية ("خدمات الأطراف الثالثة"). 
                  `
                }}
              </p>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  You acknowledge and agree that Sabri Training Center shall not be responsible for any Third-Party Services, including their
accuracy, completeness, timeliness, validity, copyright compliance, legality, decency, quality or any other aspect thereof. Sabri
Training Center does not assume and shall not have any liability or responsibility to you or any other person or entity for any
Third-Party Services.

                  ` 
                  :
                  `
                  أنت تقر وتوافق على أن مركز تدريب صبري لن يكون مسؤولاً عن أي خدمات لأطراف أخرى ، بما في ذلك
الدقة والاكتمال والتوقيت والصلاحية والامتثال لحقوق النشر والشرعية واللياقة والجودة أو أي جانب آخر من جوانبها. صبري
مركز التدريب لا يتحمل ولن يتحمل أي التزام أو مسؤولية تجاهك أو تجاه أي شخص أو كيان آخر عن أي
خدمات الطرف الثالث. 
                  `
                }}
              </p>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  Third-Party Services and links thereto are provided solely as a convenience to you and you access and use them entirely at your
own risk and subject to such third parties' terms and conditions.

                  ` 
                  : 
                  `
                  يتم توفير خدمات الجهات الخارجية والروابط الخاصة بها فقط لراحتك ويمكنك الوصول إليها واستخدامها بشكل كامل
مسؤوليتك الخاصة وتخضع لشروط وأحكام هذه الأطراف الثالثة. 
                  `
                }}
              </p>
            </div>

            <div class="uses">
              <h3 class="condH">{{ isEnglish ? `Tracking Technologies
` : `تقنيات التتبع ` }}</h3>
              <p class="condP">
                {{ 
                  isEnglish
                  ?
                  `
                  * Local Storage
                  ` 
                  : 
                  `
                  التخزين المحلي
                  `
                }}
              </p>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  Local Storage sometimes known as DOM storage, provides web apps with methods and protocols for storing client-side
data. Web storage supports persistent data storage, similar to cookies but with a greatly enhanced capacity and no
information stored in the HTTP request header.
                  ` 
                  : 
                  `
                  يُعرف التخزين المحلي أحيانًا باسم تخزين DOM ، ويوفر لتطبيقات الويب طرقًا وبروتوكولات لتخزين جانب العميل
بيانات. يدعم التخزين على الويب تخزين البيانات المستمر ، على غرار ملفات تعريف الارتباط ولكن بسعة محسّنة بشكل كبير ولا
المعلومات المخزنة في عنوان طلب HTTP. 
                  `
                }}
              </p>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  * Sessions
                  ` 
                  : 
                  `
                  * Sessions
                  `
                }}
              </p>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  uses "Sessions" to identify the areas of our website that you have visited. A Session is a small piece of data stored on
your computer or mobile device by your web browser.

                  ` 
                  :
                  `
                  يستخدم "الجلسات" لتحديد مناطق موقعنا التي قمت بزيارتها. الجلسة هي جزء صغير من البيانات المخزنة على
جهاز الكمبيوتر أو الجهاز المحمول الخاص بك عن طريق متصفح الويب الخاص بك. 
                  `
                }}
              </p>
            </div>
            <div class="uses">
              <h3 class="condH">{{ isEnglish ? `Information about General Data Protection Regulation
(GDPR)
` : `معلومات حول اللائحة العامة لحماية البيانات
(اللائحة العامة لحماية البيانات) ` }}</h3>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  We may be collecting and using information from you if you are from the European Economic Area (EEA), and in this section of
our Privacy Policy we are going to explain exactly how and why is this data collected, and how we maintain this data under
protection from being replicated or used in the wrong way.
                  ` 
                  : 
                  `
                  قد نقوم بجمع واستخدام معلومات منك إذا كنت من المنطقة الاقتصادية الأوروبية (EEA) ، وفي هذا القسم من
سياسة الخصوصية الخاصة بنا سوف نشرح بالضبط كيف ولماذا يتم جمع هذه البيانات ، وكيف نحافظ على هذه البيانات
الحماية من التكرار أو الاستخدام بطريقة خاطئة. 
                  `
                }}
              </p>
            </div>

            <div class="uses">
              <h3 class="condH">{{ isEnglish ? `What is GDPR?` : ` ما هو اللائحة العامة لحماية البيانات؟ ` }}</h3>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  GDPR is an EU-wide privacy and data protection law that regulates how EU residents' data is protected by companies and
enhances the control the EU residents have, over their personal data.

                  ` 
                  : 
                  `
                  اللائحة العامة لحماية البيانات (GDPR) هو قانون لحماية البيانات والخصوصية على مستوى الاتحاد الأوروبي ينظم كيفية حماية بيانات المقيمين في الاتحاد الأوروبي من قبل الشركات و
يعزز سيطرة المقيمين في الاتحاد الأوروبي على بياناتهم الشخصية. 
                  `
                }}
              </p>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  The GDPR is relevant to any globally operating company and not just the EU-based businesses and EU residents. Our
customers’ data is important irrespective of where they are located, which is why we have implemented GDPR controls as our
baseline standard for all our operations worldwide.
                  ` 
                  : 
                  `
                  اللائحة العامة لحماية البيانات (GDPR) ذات صلة بأي شركة تعمل عالميًا وليس فقط الشركات التي تتخذ من الاتحاد الأوروبي مقراً لها والمقيمين في الاتحاد الأوروبي. لنا
تُعد بيانات العملاء مهمة بغض النظر عن مكان تواجدهم ، ولهذا السبب قمنا بتطبيق ضوابط اللائحة العامة لحماية البيانات (GDPR) كضوابطنا
المعيار الأساسي لجميع عملياتنا في جميع أنحاء العالم. 
                  
                  `
                }}
              </p>
            </div>

            <div class="uses">
              <h3 class="condH">{{ isEnglish ? `What is personal data?` : `ما هي البيانات الشخصية؟  ` }}</h3>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  Any data that relates to an identifiable or identified individual. GDPR covers a broad spectrum of information that could be used
on its own, or in combination with other pieces of information, to identify a person. Personal data extends beyond a person’s
name or email address. Some examples include financial information, political opinions, genetic data, biometric data, IP
addresses, physical address, sexual orientation, and ethnicity.
                  ` 
                  : 
                  `
                  أي بيانات تتعلق بفرد محدد أو محدد الهوية. يغطي القانون العام لحماية البيانات (GDPR) مجموعة واسعة من المعلومات التي يمكن استخدامها
بمفردها ، أو بالاشتراك مع أجزاء أخرى من المعلومات ، لتحديد هوية الشخص. تمتد البيانات الشخصية إلى ما هو أبعد من بيانات الشخص
الاسم أو عنوان البريد الإلكتروني. تتضمن بعض الأمثلة المعلومات المالية والآراء السياسية والبيانات الوراثية وبيانات القياسات الحيوية والملكية الفكرية
العناوين والعنوان المادي والتوجه الجنسي والعرق. 
                  `
                }}
              </p>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  The Data Protection Principles include requirements such as:
                  ` 
                  : 
                  `
                  تتضمن مبادئ حماية البيانات متطلبات مثل: 
                  `
                }}
              </p>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  * Personal data collected must be processed in a fair, legal, and transparent way and should only be used in a way that a
person would reasonably expect.
                  
                  ` 
                  : 
                  `
                  * يجب معالجة البيانات الشخصية التي تم جمعها بطريقة عادلة وقانونية وشفافة ويجب استخدامها فقط بالطريقة التي أ
يتوقع الشخص بشكل معقول. 
                  
                  `
                }}
              </p>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  * Personal data should only be collected to fulfil a specific purpose and it should only be used for that purpose.
Organizations must specify why they need the personal data when they collect it.
                  ` 
                  : 
                  `
                  * يجب جمع البيانات الشخصية فقط لتحقيق غرض محدد ويجب استخدامها لهذا الغرض فقط.
يجب أن تحدد المنظمات سبب حاجتها للبيانات الشخصية عند جمعها. 
                  
                  `
                }}
              </p>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  * Personal data should be held no longer than necessary to fulfil its purpose.
                  ` 
                  : 
                  `
                  * يجب ألا يتم الاحتفاظ بالبيانات الشخصية لفترة أطول من اللازم لتحقيق الغرض منها.
                  `
                }}
              </p>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  * People covered by the GDPR have the right to access their own personal data. They can also request a copy of their
data, and that their data be updated, deleted, restricted, or moved to another organization.
                  ` 
                  : 
                  `
                  * يحق للأشخاص المشمولين باللائحة العامة لحماية البيانات الوصول إلى بياناتهم الشخصية. يمكنهم أيضًا طلب نسخة من ملفات
البيانات ، وأن يتم تحديث بياناتهم أو حذفها أو تقييدها أو نقلها إلى مؤسسة أخرى. 
                  `
                }}
              </p>
            </div>

            <div class="uses">
              <h3 class="condH">{{ isEnglish ? `Why is GDPR important?` : `ما سبب أهمية القانون العام لحماية البيانات (GDPR)؟  ` }}</h3>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  GDPR adds some new requirements regarding how companies should protect individuals' personal data that they collect and
process. It also raises the stakes for compliance by increasing enforcement and imposing greater fines for breach. Beyond
these facts it's simply the right thing to do. At Sabri Training Center we strongly believe that your data privacy is very important
and we already have solid security and privacy practices in place that go beyond the requirements of this new regulation.

                  ` 
                  : 
                  `
                  يضيف القانون العام لحماية البيانات بعض المتطلبات الجديدة فيما يتعلق بكيفية حماية الشركات للبيانات الشخصية للأفراد التي تجمعها و
معالجة. كما أنه يزيد من مخاطر الامتثال من خلال زيادة الإنفاذ وفرض غرامات أكبر على الخرق. وراء - فى الجانب الاخر
هذه الحقائق هي ببساطة الشيء الصحيح الذي ينبغي عمله. في مركز صبري للتدريب نؤمن بشدة أن خصوصية بياناتك مهمة للغاية
ولدينا بالفعل ممارسات أمنية وخصوصية قوية تتجاوز متطلبات هذه اللائحة الجديدة. 
                  `
                }}
              </p>
            </div>

            <div class="uses">
              <h3 class="condH">{{ isEnglish ? `Individual Data Subject's Rights - Data Access,
Portability and Deletion` : `حقوق صاحب البيانات الفردية - الوصول إلى البيانات ،
قابلية النقل والحذف  ` }}</h3>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  We are committed to helping our customers meet the data subject rights requirements of GDPR. Sabri Training Center
processes or stores all personal data in fully vetted, DPA compliant vendors. We do store all conversation and personal data for
up to 6 years unless your account is deleted. In which case, we dispose of all data in accordance with our Terms of Service and
Privacy Policy, but we will not hold it longer than 60 days.
                  ` 
                  : 
                  `
                  نحن ملتزمون بمساعدة عملائنا على تلبية متطلبات حقوق موضوع البيانات الواردة في القانون العام لحماية البيانات (GDPR). مركز تدريب صبري
يعالج أو يخزن جميع البيانات الشخصية في بائعين تم فحصهم بالكامل ومتوافقين مع إدارة حماية البيانات. نقوم بتخزين جميع المحادثات والبيانات الشخصية لـ
تصل إلى 6 سنوات ما لم يتم حذف حسابك. في هذه الحالة ، نتخلص من جميع البيانات وفقًا لشروط الخدمة و
سياسة الخصوصية ، لكننا لن نحتفظ بها لمدة تزيد عن 60 يومًا. 
                  `
                }}
              </p>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  We are aware that if you are working with EU customers, you need to be able to provide them with the ability to access, update,
retrieve and remove personal data. We got you! We've been set up as self service from the start and have always given you
access to your data and your customers data. Our customer support team is here for you to answer any questions you might
have about working with the API.

                  ` 
                  : 
                  `
                  نحن ندرك أنه إذا كنت تعمل مع عملاء من الاتحاد الأوروبي ، فيجب أن تكون قادرًا على تزويدهم بالقدرة على الوصول والتحديث و
استرداد وإزالة البيانات الشخصية. وصلنا لك! لقد تم إعدادنا كخدمة ذاتية منذ البداية وقدمنا لك دائمًا
الوصول إلى بياناتك وبيانات عملائك. فريق دعم العملاء لدينا هنا من أجلك للإجابة على أي أسئلة قد ترغب فيها
لديك حول العمل مع API. 
                  `
                }}
              </p>
            </div>

            <div class="uses">
              <h3 class="condH">{{ isEnglish ? `Contact Us` : `اتصل بنا ` }}</h3>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  Don't hesitate to contact us if you have any questions.

                  ` 
                  : 
                  `
                  لا تتردد في الاتصال بنا إذا كان لديك أي أسئلة. 
                  `
                }}
              </p>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  * Via Phone Number: +249907249203
                  ` 
                  : 
                  `
                  * عبر رقم الهاتف: 249907249203+ 
                  `
                }}
              </p>
            </div>

          </div>
      </div>
      </div>
    </div>
  </section>
</template>

<script>
import {mapState} from 'vuex'

export default {
  name: 'Privacy',
  data () {
    return {
    }
  },

  computed: {
    ...mapState('settings', ['isEnglish'])
  }
}
</script>
<style lang="scss">
@import "src/assets/css/sass/helpers/_variabels.scss";
@import "src/assets/css/sass/helpers/_mixins.scss";

.uses {
    margin-top: 1rem !important;
}

.profile {
    .titel {
        img {
            opacity: 1;
        }
        h3 {
            font-family: "cairoB";
            font-size: 18px;
            color: #787878;
            margin: -29px 18px 39px 0;
        }
    }
    .cn-pay {
        padding: 0 10.1%;
        display: block;
        /*--box-pay--*/
        .box-pay {
            margin: 0 0 30px 0;
            .inv {
                text-align: center;
                .box {
                    border: 1px solid #ddd;
                    border-radius: 62px;
                    max-width: 80%;
                    display: block;
                    height: 40px;
                    padding: 5px 0 0 0;
                    margin: 0 auto 12px auto;

                    h2 {
                        display: inline-block;
                        font-family: "cairoR";
                        font-size: 15px;
                        color: #7b86fa;
                        span {
                            color: #fcd462;
                        }
                    }
                    img {
                        display: inline-block;
                        width: 30px;
                        margin: -9px 0 0 0;
                    }
                    svg {  
                        display: none;
                        width: 46px;
                        margin: -11px 0 0 0;
                    }
                }
                .detaii {
                    border-radius: 62px;
                    max-width: 80%;
                    display: block;
                    height: 45px;
                    padding: 11px 0 0 0;
                    background-color: #7b86fa;
                    position: relative;
                    top: -6px;
                    text-align: center;
                    margin: 0 auto;
                    a{
                        display: block;
                        font-family: "cairoR";
                        font-size: 15px;
                        color: #fff;
                        text-decoration: none;
                    }
                    svg {  
                        margin: 0 0 0 0;
                    }
                }
            }
            .data {
                text-align: center;
                background: #fff;
                box-shadow: 4px 8px 9px #e5e4e4;
                padding: 53px 0;
                height: 237px;
                border-radius: 32px;
                img {
                    width: 70px;
                    text-align: center;
                    margin: 0 0 12px 0;
                }
                h2 {
                    font-family: "cairoR";
                    font-size: 19px;
                    color: #32ba7c;
                    margin: 0 0 10px 0;
                }
                p {
                    font-family: "cairoR";
                    font-size: 16px;
                    color: #313131;
                }
            }
        }
        /*--box-done--*/
        .box-done {
            .inv {
                opacity: 1;
                .box {
                    opacity: 1;
                    h2 {
                        opacity: 1;
                        span {
                            opacity: 1;
                        }
                    }
                    img {
                        opacity: 1;
                    }
                }
                svg {  
                   opacity: 1;
                }
            }
            .data {
                opacity: 1;
                img {
                    opacity: 1;
                }
                h2 {
                    opacity: 1;
                }
                p {
  opacity: 1;
                }
            }
        }
        /*--box-wait--*/
        .box-wait {
            .inv {
                opacity: 1;
                .box {
                    opacity: 1;
                    h2 {
                        opacity: 1;
                        span {
                            opacity: 1;
                        }
                    }
                    img {
                        opacity: 1;
                    }
                }
                svg {  
                   opacity: 1;
                }
            }
            .data {
                opacity: 1;
                img {
                    opacity: 1;
                }
                h2 {
                    color: #7b86fa;
                }
                p {
                    opacity: 1;
                }
            }
        }
        /*--box-unacceptable--*/
        .box-unacceptable {
            .inv {
                opacity: 1;
                .box {
                    opacity: 1;
                    h2 {
                        opacity: 1;
                        span {
                            opacity: 1;
                        }
                    }
                    img {
                        opacity: 1;
                    }
                }
                svg {  
                   opacity: 1;
                }
            }
            .data {
                opacity: 1;
                img {
                    opacity: 1;
                }
                h2 {
                    color: #ff5f5a;
                }
                p {
                    opacity: 1;
                }
            }
        }
        /*--pending-request--*/
        .pending-request {
            opacity: 1;
            .inv {
                opacity: 1;
                .box {
                    opacity: 1;
                    h2 {
                        opacity: 1;
                        span {
                            opacity: 1;
                        }
                    }
                    img {
                        opacity: 1;
                    }
                }
                svg {  
                   opacity: 1;
                }
            }
            .data {
                padding: 24px 0 0 0;
                img {
                    width: 35px;
                }
                h2 {
                    color: #dc8638;
                    display: inline-block;
                    margin: 0 5px 0 0
                }
                .money {
                    background: #D97A22;
                    max-width: 201px;
                    margin: 27px auto 0 auto;
                    border-radius: 30px;
                    padding: 10px 0 10px 0;
                    h3 {
                        display: inline-block;
                        font-family: "cairoB";
                        font-size: 15px;
                        color: #fff;
                        margin: 0 -17px 10px 0;
                    }
                    .price {
                        display: inline-block;
                        background: #FCD462;
                        border-radius: 37px;
                        float: left;
                        position: relative;
                        left: 6px;
                        top: -2px;
                        h4 {
                            font-size: 15px;
                            font-family: "cairoB";
                            padding: 8px 15px 0 15px;
                            color: #787878;
                            span {
                                color: #fff;
                                margin: 0 0 0 6px;
                            }
                        }
                    }
                }
                .viewpay {
                    opacity: 1;
                    .box {
                        max-width: 180px;
                        margin: 0 auto;
                        background: #fad25e;
                        padding: 9px 0 9px 0;
                        border-radius: 34px;
                        cursor: pointer;
                        img {
                            opacity: 1;
                        }
                        h2 {
                            color: #787878;
                            display: inline-block;
                            margin: 0 5px 0 0;
                            font-size: 18px;
                        }
                    }
                    svg {
                        width: 80px;
                        position: relative;
                        top: 1px;
                    }
                }
            }
        }
    }
    .msPay{
        display: none;
        margin: 0 auto;
        text-align: center;
        h3{
            font-size: 19px;
            font-family: 'cairoR';
            color: #7B7B7B;
            margin: 35px 0 0 0;
        }
    }
    .cer{
        background-color: #3A54A1;
        width: 841px;
        height: 595px;
        margin: 0 auto 30px auto;
        padding: 20px;
        position: relative;
        overflow: hidden;
        .backg{
            position: absolute;
            top: 0; 
            z-index: 4;
        }
        .boodW{
            background-color: #fff;
            padding: 25px;
            height: 555px;
            position: relative;
            svg{
                position:absolute;
                top: 0;
                left: 0;
                right: 0;
            }
            .heddd{
                margin: 0 0 0 0;
                text-align: center;
                position: relative;
                z-index: 5;
                .left{
                    float: right;
                    margin: -9px 0 0 0;
                }
                .right{
                    float: left;
                }
                span{
                    font-size: 16px;
                    color: #5D5D5D;
                    font-family: 'segoR';
                }
                h2{
                    font-size: 26px;
                    color: #2F2F2F;
                    font-family: 'segoI';
                }
                img{
                    margin: 10px 0 0 0;
                }
            }
            .name{
                text-align: center;
                position: relative;
                margin: 7px 0 0 0;
                z-index: 5;
                h3{
                    font-size: 30px;
                    color: #1A1818;
                    font-family: 'segoB';
                }
                svg{
                    position: absolute;
                    left: 0;
                    right: 0;
                    top: 39px;
                    margin: 0 auto;     
                }
                span{
                    font-size: 16px;
                    color: #5D5D5D;
                    font-family: 'segoI';
                    display: block;
                    margin: 15px 0 0 0;
                }
                h4{
                    color: #1A1818;
                    font-size: 26px;
                    font-family: 'segosR';
                    margin: 12px 0 0 0;
                }
            }
            .detaills{
                margin: 20px 0 0 0;
                padding: 0 109px 0 109px;
                .hours{
                    position: relative;
                    z-index: 5;
                    text-align: left;
                    width: 146px;
                    display: inline-block;
                    span{
                        font-size: 16px;
                        color: #5D5D5D;
                        font-family: 'segoI';
                    }
                    h3{
                        display: inline-block;
                        font-family: 'segosB';
                        font-size: 23px;
                        color: #1A1818;
                        span{
                            display: inline-block;
                            color: #1A1818;
                            margin-left: 11px;
                        }
                    }
                }
                .date{
                    position: relative;
                    z-index: 5;
                    text-align: left;
                    width: 382px;
                    display: inline-block;
                    h4{
                        font-size: 16px;
                        color: #5D5D5D;
                        font-family: 'segoI';
                    }
                    h3{
                        display: inline-block;
                        font-family: 'segoB';
                        color: #1A1818;
                        font-size: 18px;
                        margin-right: 10px;
                    }
                    span{
                        font-size: 16px;
                        color: #5D5D5D;
                        font-family: 'segoI';
                        display: inline-block;
                        margin-right: 10px;
                    }
                }
            }
            .ended{
                position: relative;
                z-index: 5;
                margin: 10px 0 0 0;
                ul{
                    li{
                        list-style: none;
                        display: inline-block;
                        margin-right: 38px;
                        margin-left: 35px;
                        text-align: left;
                        span{
                            color: #1A1818;
                            font-family: 'segoI';
                            font-size: 17px;
                        }
                        h3{
                            font-size: 15px;
                            color: #5D5D5D;
                            font-family: 'segoI';
                        }
                    }
                }
            }
            .number{
                position: relative;
                z-index: 5;
                margin: -6px 0 0 0;
                ul{
                    li{
                        list-style: none;
                        display: inline-block;
                        margin-right: 34px;
                        margin-left: 2px;
                        h3{
                            display: inline-block;
                            font-size: 13px;
                            color: #5D5D5D;
                            font-family: 'segoI';
                            span{
                                font-size: 16px;
                                display: inline-block;
                                color: #5D5D5D;
                                font-family: 'segoI';
                            }
                        }
                    }
                }
            }
        }
    }


    .downlodd{
        margin: 0 auto 40px auto;
        text-align: center;
        button{
            font-size: 16px;
            color: #fff;
            font-family: 'cairoR';
            background-color: #7B86FA;
            width: 183px;
            height: 46px;
            transition: all ease-in-out .4s;
            outline: 0;
            &:hover{
                background-color: #fad25e;
                color: #1A1818;
            }
        }
    }


    /*الاسئلة الشائعــــــة*/
    .faq{
        max-width: 726px;
        margin: 0 auto;
        .accord{
            padding: 0 10px 0 10px;
            .card{
                margin: 0 0 10px 0;
                border: 0;
                .card-header{
                    background-color: #7B86FA;
                    border-bottom:2px solid #F2F2F2;
                    padding: 0;
                    a{
                        color: #fff;
                        font-size: 16px;
                        font-family: 'cairoR';
                        cursor: pointer;
                        //maxMobile
                        @media(max-width:767px){
                            font-size: 15px;
                        }
                        .linke{
                            background-color: #6D76D8;
                            width: 49px;
                            height: 52px;
                            display: inline-block;
                            text-align: center;
                            margin:0 -20px 0 9px;
                            line-height:3;
                        }
                    }
                }
                .collapse{
                    .card-body{
                        background-color: #fff;
                        p{
                            font-size: 16px;
                            color: #5D5D5D;
                            font-family: 'cairoR';
                        }
                    }
                }
            }
        }
    }

    /* سياســة الخصوصيــة*/

    .privacy{

        .Conditions{
            margin-bottom: 40px;
            .condH{
                color: #fff;
                font-family: 'cairoB';
                font-size:18px;
                padding: 10px;
                background-color: #7B86FA;
                margin-bottom: 20px;
            }
            .condP{
                font-family: 'cairoR';
                font-size: 16px;
                color: $textColor;
                margin: 0;
            }
        }

        .uses{
            .condH{
                color: #fff;
                font-family: 'cairoB';
                font-size:18px;
                padding: 10px;
                background-color: #7B86FA;
                margin-bottom: 20px;
            }
            .condP{
                font-family: 'cairoR';
                font-size: 16px;
                color: $textColor;
                margin: 0;
            }
        }
    }
}
</style>
