<template>
  <main class="legal-page">
    <header class="legal-page__hero">
      <h1>{{ isEnglish ? 'Privacy Policy' : 'سياسة الخصوصية' }}</h1>
    </header>

    <section class="legal-page__content">
            <div class="Conditions"> 
              <h3 class="condH">{{ isEnglish ? 'Important note' : 'ملاحظة مهمة' }}</h3>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                    Sabri Training Center (“we,” “our,” or “us”) is committed to protecting your privacy. This Privacy Policy explains how your personal
information is collected, used, and disclosed by Sabri Training Center.
This Privacy Policy applies to our website, and its associated subdomains (collectively, our “Service”) alongside our application,
Sabri Training Center. By accessing or using our Service, you signify that you have read, understood, and agree to our collection,
storage, use, and disclosure of your personal information as described in this Privacy Policy and our Terms of Service.
                  ` 
                  : 
                  `
                  يلتزم مركز د. صبري أبوقرون للتدريب («نحن» أو «لنا» أو «خاصتنا») بحماية خصوصيتك. توضّح سياسة الخصوصية هذه كيفية جمع معلوماتك الشخصية واستخدامها والإفصاح عنها من قِبَل مركز د. صبري أبوقرون للتدريب.
تسري سياسة الخصوصية هذه على موقعنا الإلكتروني ونطاقاته الفرعية المرتبطة به (يُشار إليها مجتمعةً بـ«الخدمة»)، إلى جانب تطبيقنا مركز د. صبري أبوقرون للتدريب. بدخولك إلى الخدمة أو استخدامها، فإنك تُقرّ بأنك قرأت هذه السياسة وفهمتها ووافقت على جمع معلوماتك الشخصية وتخزينها واستخدامها والإفصاح عنها وفق ما هو موضّح في سياسة الخصوصية هذه وشروط الخدمة الخاصة بنا.
                  `
                }}
                

              </p>
            </div>

            <div class="uses">
              <h3 class="condH">{{ isEnglish ? `Definitions and key terms` : `التعريفات والمصطلحات الرئيسية` }}</h3>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                    To help explain things as clearly as possible in this Privacy Policy, every time any of these terms are referenced, are strictly
defined as:
                  ` 
                  : 
                  `
                  لتوضيح المصطلحات الواردة في سياسة الخصوصية هذه بأكبر قدر ممكن من الدقة، تُعرَّف كل مرة يُشار فيها إلى أيٍّ من المصطلحات التالية تعريفًا محددًا وصارمًا على النحو الآتي:
                  `
                }}
              </p>
              <br>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  * Cookie: small amount of data generated by a website and saved by your web browser. It is used to identify your browser,
provide analytics, remember information about you such as your language preference or login information.

                  ` 
                  : 
                  `
                  * ملف تعريف الارتباط (Cookie): قدر صغير من البيانات تُنشئه موقع ويب ويخزّنه متصفحك. يُستخدَم لتعريف متصفحك، وتقديم تحليلات الاستخدام، وتذكّر معلومات عنك كتفضيل اللغة وبيانات تسجيل الدخول.
                  `
                }}
              </p>
              <br>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                    * Company: when this policy mentions “Company,” “we,” “us,” or “our,” it refers to Sabri Training Center, Khartoum, obid khatim
st that is responsible for your information under this Privacy Policy.

                  ` 
                  : 
                  `
                  * الجهة المسؤولة: عند ورود مصطلح «الشركة» أو «نحن» أو «لنا» أو «خاصتنا» في هذه السياسة، فإنه يُقصد به مركز د. صبري أبوقرون للتدريب، الخرطوم، شارع عبيد خاتم، وهو الجهة المسؤولة عن معلوماتك بموجب سياسة الخصوصية هذه.
                  `
                }}
              </p>
              <br>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                    * Country: where Sabri Training Center or the owners/founders of Sabri Training Center are based, in this case is Sudan

                  ` 
                  : 
                  `
                  * الدولة: الدولة التي يتخذ منها مركز د. صبري أبوقرون للتدريب أو مالكوه ومؤسسوه مقرًّا لهم، وهي في هذه الحالة جمهورية السودان.
                  `
                }}
              </p>
              <br>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                    * Customer: refers to the company, organization or person that signs up to use the Sabri Training Center Service to manage
the relationships with your consumers or service users.

                  ` 
                  : 
                  `
                  * العميل: الشركة أو المؤسسة أو الشخص الذي اشترك في استخدام خدمة مركز د. صبري أبوقرون للتدريب بهدف إدارة علاقاته مع مستهلكيه أو مستخدمي خدماته.
                  `
                }}
              </p>
              <br>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                    * Device: any internet connected device such as a phone, tablet, computer or any other device that can be used to visit
Sabri Training Center and use the services.

                  ` 
                  : 
                  `
                  * الجهاز: أي جهاز متصل بالإنترنت، كالهاتف الذكي أو الجهاز اللوحي أو الحاسوب أو أي جهاز آخر يمكن استخدامه لزيارة مركز د. صبري أبوقرون للتدريب واستخدام خدماته.
                  `
                }}
              </p>
              <br>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                    * IP address: Every device connected to the Internet is assigned a number known as an Internet protocol (IP) address.
These numbers are usually assigned in geographic blocks. An IP address can often be used to identify the location from
which a device is connecting to the Internet.

                  ` 
                  : 
                  `
                  * عنوان IP: رقم يُعرف ببروتوكول الإنترنت (IP) يُخصَّص لكل جهاز متصل بالشبكة. تُوزَّع هذه الأرقام عادةً وفق كتل جغرافية، ويمكن الاستعانة بعنوان IP في الغالب لتحديد الموقع الجغرافي الذي يتصل منه الجهاز بالإنترنت.
                  `
                }}
              </p>
              <br>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  * Personnel: refers to those individuals who are employed by Sabri Training Center or are under contract to perform a
service on behalf of one of the parties.

                  ` 
                  : 
                  `
                  * الكوادر البشرية: الأفراد العاملون لدى مركز د. صبري أبوقرون للتدريب بموجب عقد عمل، أو المتعاقدون معهم لأداء خدمة نيابةً عن أيٍّ من الأطراف.
                  `
                }}
              </p>
              <br>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                    * Personal Data: any information that directly, indirectly, or in connection with other information — including a personal
identification number — allows for the identification or identifiability of a natural person.

                  ` 
                  : 
                  `
                  * البيانات الشخصية: أي معلومات تُتيح، بصورة مباشرة أو غير مباشرة أو بالاقتران مع معلومات أخرى — بما فيها أرقام التعريف الشخصي — تحديد هوية شخص طبيعي أو إمكانية التعرف عليه.
                  `
                }}
              </p>
              <br>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                    * Service: refers to the service provided by Sabri Training Center as described in the relative terms (if available) and on this
platform.

                  ` 
                  : 
                  `
                  * الخدمة: الخدمة التي يقدّمها مركز د. صبري أبوقرون للتدريب، كما هو موضّح في الشروط ذات الصلة (إن وُجدت) وعلى هذه المنصة.
                  `
                }}
              </p>
              <br>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                    * Third-party service: refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide
our content or whose products or services we think may interest you.
                  ` 
                  : 
                  `
                  * خدمات الأطراف الثالثة: تشمل المعلنين ورعاة المسابقات والشركاء في التسويق والترويج وغيرهم ممن يوفّرون محتوانا، أو الذين نرى أن منتجاتهم أو خدماتهم قد تستأثر باهتمامك.
                  `
                }}
              </p>
              <br>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                    * Website: Sabri Training Center’s site, which can be accessed via this URL: stc.training
                  ` 
                  : 
                  `
                  * الموقع الإلكتروني: موقع مركز د. صبري أبوقرون للتدريب، ويمكن الوصول إليه عبر الرابط: stc.training
                  `
                }}
              </p>
              <br>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  * You: a person or entity that is registered with Sabri Training Center to use the Services.
                  ` 
                  : 
                  `
                  * أنت: الشخص الطبيعي أو الاعتباري المسجَّل في مركز د. صبري أبوقرون للتدريب بهدف استخدام الخدمات.
                  `
                }}
              </p>
              <br>
            </div>
            <div class="uses">
              <h3 class="condH">{{ isEnglish ? `You: a person or entity that is registered with Sabri Training Center to use the Services.
` : `ما المعلومات التي نجمعها؟` }}</h3>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                    We collect information from you when you visit our website, register on our site, place an order, subscribe to our newsletter,
respond to a survey or fill out a form.

                  ` 
                  : 
                  `
                  نجمع معلومات منك عند زيارتك موقعنا الإلكتروني، أو تسجيلك فيه، أو تقديمك طلبًا، أو اشتراكك في نشرتنا الإخبارية، أو إجابتك على استطلاع، أو تعبئتك نموذجًا.
                  `
                }}
              </p>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  * Name / Usernam
                  `
                  :
                  `
                  * الاسم / اسم المستخدم
                  `
                }}
              </p>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  * Phone Numbers
                  `
                  :
                  `
                  * أرقام الهاتف
                  `
                }}
              </p>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  * Email Addresses
                  `
                  :
                  `
                  * عناوين البريد الإلكتروني
                  `
                }}
              </p>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  * Password
                  `
                  :
                  `
                  * كلمة المرور
                  `
                }}
              </p>
              <br>
            </div>

            <div class="uses">
              <h3 class="condH">{{ isEnglish ? `When does Sabri Training Center use end user
information from third parties?` : `متى يستخدم مركز د. صبري أبوقرون للتدريب معلومات المستخدم النهائي الواردة من أطراف ثالثة؟` }}</h3>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  Sabri Training Center will collect End User Data necessary to provide the Sabri Training Center services to our customers. End
users may voluntarily provide us with information they have made available on social media websites. If you provide us with any
such information, we may collect publicly available information from the social media websites you have indicated. You can
control how much of your information social media websites make public by visiting these websites and changing your privacy
settings.
                  ` 
                  : 
                  `
                  يجمع مركز د. صبري أبوقرون للتدريب بيانات المستخدم النهائي اللازمة لتقديم خدماته لعملائنا. وقد يُزوّدنا المستخدمون النهائيون طوعًا بمعلومات أتاحوها على مواقع التواصل الاجتماعي. وفي حال زوّدتنا بأي من هذه المعلومات، قد نجمع ما هو متاح للعموم منها من تلك المواقع التي أشرت إليها. ويمكنك التحكم في قدر المعلومات التي تُظهرها مواقع التواصل الاجتماعي بزيارة إعدادات الخصوصية في تلك المواقع وتعديلها.
                  `
                }}
              </p>
              <br>
            </div>

            <div class="uses">
              <h3 class="condH">{{ isEnglish ? `When does Sabri Training Center use customer
information from third parties?` : `متى يستخدم مركز د. صبري أبوقرون للتدريب معلومات العملاء الواردة من أطراف ثالثة؟` }}</h3>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  We receive some information from the third parties when you contact us. For example, when you submit your email address to
us to show interest in becoming a Sabri Training Center customer, we receive information from a third party that provides
automated fraud detection services to Sabri Training Center. We also occasionally collect information that is made publicly
available on social media websites. You can control how much of your information social media websites make public by visiting
these websites and changing your privacy settings.
                  ` 
                  : 
                  `
                  نتلقى بعض المعلومات من أطراف ثالثة حين تتواصل معنا. فعلى سبيل المثال، حين تُرسل إلينا عنوان بريدك الإلكتروني للتعبير عن رغبتك في الانضمام إلى عملاء مركز د. صبري أبوقرون للتدريب، نتلقى معلومات من طرف ثالث يُوفّر لمركز د. صبري أبوقرون للتدريب خدمات الكشف الآلي عن الاحتيال. كما نجمع أحيانًا معلومات منشورة للعموم على مواقع التواصل الاجتماعي. ويمكنك التحكم في قدر ما تُتيحه مواقع التواصل الاجتماعي من معلوماتك للعموم بزيارة تلك المواقع وتعديل إعدادات الخصوصية فيها.
                  `
                }}
              </p>
              <br>
            </div>
            <div class="uses">
              <h3 class="condH">{{ isEnglish ? `Do we share the information we collect with third
parties?` : `هل نشارك المعلومات التي نجمعها مع أطراف ثالثة؟` }}</h3>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  We may share the information that we collect, both personal and non-personal, with third parties such as advertisers, contest
sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may
interest you. We may also share it with our current and future affiliated companies and business partners, and if we are involved
in a merger, asset sale or other business reorganization, we may also share or transfer your personal and non-personal
information to our successors-in-interest.
                  ` 
                  : 
                  `
                  قد نُشارك المعلومات التي نجمعها، سواء أكانت شخصية أم غير شخصية، مع أطراف ثالثة كالمعلنين ورعاة المسابقات والشركاء في التسويق والترويج وغيرهم ممن يُوفّرون محتوانا، أو الذين نرى أن منتجاتهم أو خدماتهم قد تُثير اهتمامك. كما يجوز لنا مشاركتها مع شركاتنا التابعة الحالية والمستقبلية وشركاء الأعمال. وفي حال انخراطنا في عملية اندماج أو بيع أصول أو إعادة هيكلة تجارية، يجوز لنا أيضًا مشاركة معلوماتك الشخصية وغير الشخصية أو نقلها إلى الخلفاء في الحقوق.
                  `
                }}
              </p>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  We may engage trusted third party service providers to perform functions and provide services to us, such as hosting and
maintaining our servers and the website, database storage and management, e-mail management, storage marketing, credit card
processing, customer service and fulfilling orders for products and services you may purchase through the website. We will
likely share your personal information, and possibly some non-personal information, with these third parties to enable them to
perform these services for us and for you.
                  ` 
                  : 
                  `
                  قد نستعين بمزوّدي خدمات من أطراف ثالثة موثوقة لأداء وظائف وتقديم خدمات لنا، كاستضافة خوادمنا وموقعنا الإلكتروني وصيانتهما، وتخزين قواعد البيانات وإدارتها، وإدارة البريد الإلكتروني، والتسويق، ومعالجة بطاقات الائتمان، وخدمة العملاء، وتنفيذ الطلبات المتعلقة بالمنتجات والخدمات التي قد تشتريها عبر الموقع. وسنُشارك على الأرجح معلوماتك الشخصية، وربما بعض المعلومات غير الشخصية، مع هذه الأطراف الثالثة لتمكينها من أداء هذه الخدمات نيابةً عنّا ولصالحك.
                  `
                }}
              </p>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  We may share portions of our log file data, including IP addresses, for analytics purposes with third parties such as web
analytics partners, application developers, and ad networks. If your IP address is shared, it may be used to estimate general
location and other technographics such as connection speed, whether you have visited the website in a shared location, and
type of the device used to visit the website. They may aggregate information about our advertising and what you see on the
website and then provide auditing, research and reporting for us and our advertisers.

                  ` 
                  : 
                  `
                  يجوز لنا مشاركة أجزاء من بيانات ملفات السجل لدينا، بما فيها عناوين IP، مع أطراف ثالثة لأغراض التحليلات، كشركاء تحليل الويب ومطوّري التطبيقات والشبكات الإعلانية. وقد يُستخدَم عنوان IP الخاص بك، إذا جرت مشاركته، لتقدير الموقع الجغرافي العام وغيره من المعطيات التقنية كسرعة الاتصال وما إذا كنت قد زرت الموقع من موقع مشترك، ونوع الجهاز المستخدم للزيارة. وقد يُجمّع هؤلاء معلومات حول إعلاناتنا وما تراه على الموقع، ثم يُوفّرون لنا ولمعلنينا خدمات التدقيق والبحث وإعداد التقارير.
                  `
                }}
              </p>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  We may also disclose personal and non-personal information about you to government or law enforcement officials or private
parties as we, in our sole discretion, believe necessary or appropriate in order to respond to claims, legal process (including
subpoenas), to protect our rights and interests or those of a third party, the safety of the public or any person, to prevent or
stop any illegal, unethical, or legally actionable activity, or to otherwise comply with applicable court orders, laws, rules and
regulations.
                  ` 
                  : 
                  `
                  قد نُفصح أيضًا عن معلومات شخصية وغير شخصية تخصّك إلى جهات حكومية أو جهات إنفاذ القانون أو أطراف من القطاع الخاص، متى رأينا — وفق تقديرنا المنفرد — أن ذلك ضروري أو مناسب للاستجابة للمطالبات والإجراءات القانونية (بما فيها أوامر الاستدعاء القضائي)، أو لحماية حقوقنا ومصالحنا أو حقوق ومصالح طرف ثالث، أو لصون أمن العموم أو أي فرد، أو لمنع أي نشاط غير قانوني أو غير أخلاقي أو موجب للمساءلة القانونية أو وقفه، أو للامتثال لأوامر المحاكم والقوانين واللوائح المعمول بها.
                  `
                }}
              </p>
              <br>
            </div>

            <div class="uses">
              <h3 class="condH">{{ isEnglish ? `Where and when is information collected from
customers and end users?` : `من أين ومتى تُجمَع المعلومات من العملاء والمستخدمين النهائيين؟` }}</h3>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  Sabri Training Center will collect personal information that you submit to us. We may also receive personal information about
you from third parties as described above.
                  ` 
                  : 
                  `
                  يجمع مركز د. صبري أبوقرون للتدريب المعلومات الشخصية التي تُقدّمها إلينا، كما قد نتلقى معلومات شخصية عنك من أطراف ثالثة على النحو الموضّح أعلاه.
                  `
                }}
              </p>
              <br>
            </div>

            <div class="uses">
              <h3 class="condH">{{ isEnglish ? `How Do We Use The Information We Collect?` : `كيف نستخدم المعلومات التي نجمعها؟` }}</h3>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  Any of the information we collect from you may be used in one of the following ways:

                  ` 
                  : 
                  `
                  يجوز استخدام أي من المعلومات التي نجمعها منك بإحدى الطرق التالية:
                  `
                }}
              </p>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  * To personalize your experience (your information helps us to better respond to your individual needs)
                  ` 
                  :
                  `
                  * لتخصيص تجربتك (تُساعدنا معلوماتك على تلبية احتياجاتك الفردية بصورة أفضل)
                  `
                }}
              </p>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  * To improve our website (we continually strive to improve our website offerings based on the information and feedback
we receive from you)

                  ` 
                  : 
                  `
                  * لتحسين موقعنا الإلكتروني (نسعى باستمرار إلى تطوير ما يتيحه موقعنا استنادًا إلى المعلومات والملاحظات التي نتلقاها منك)
                  `
                }}
              </p>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  * To improve customer service (your information helps us to more effectively respond to your customer service requests
and support needs)

                  ` 
                  : 
                  `
                  * لتحسين خدمة العملاء (تُساعدنا معلوماتك على الاستجابة بصورة أكثر فاعلية لطلبات دعمك واستفساراتك)
                  `
                }}
              </p>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  * To process transactions
                  ` 
                  : 
                  `
                  * لمعالجة المعاملات المالية
                  `
                }}
              </p>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  * To administer a contest, promotion, survey or other site feature
                  ` 
                  : 
                  `
                  * لإدارة مسابقة أو عرض ترويجي أو استطلاع أو أي ميزة أخرى في الموقع
                  `
                }}
              </p>
              <br>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  * To send periodic emails
                  ` 
                  : 
                  `
                  * لإرسال رسائل إلكترونية دورية
                  `
                }}
              </p>
              <br>
            </div>

            <div class="uses">
              <h3 class="condH">{{ isEnglish ? 'How Do We Use Your Email Address?' : 'كيف نستخدم عنوان بريدك الإلكتروني؟' }}</h3>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  By submitting your email address on this website, you agree to receive emails from us. You can cancel your participation in any
of these email lists at any time by clicking on the opt-out link or other unsubscribe option that is included in the respective
email. We only send emails to people who have authorized us to contact them, either directly, or through a third party. We do
not send unsolicited commercial emails, because we hate spam as much as you do. By submitting your email address, you also
agree to allow us to use your email address for customer audience targeting on sites like Facebook, where we display custom
advertising to specific people who have opted-in to receive communications from us. Email addresses submitted only through
the order processing page will be used for the sole purpose of sending you information and updates pertaining to your order. If,
however, you have provided the same email to us through another method, we may use it for any of the purposes stated in this
Policy. Note: If at any time you would like to unsubscribe from receiving future emails, we include detailed unsubscribe
instructions at the bottom of each email.
                  ` 
                  : 
                  `
                  بتقديم عنوان بريدك الإلكتروني على هذا الموقع، فإنك توافق على تلقّي رسائل منّا. ويمكنك إلغاء اشتراكك في أي من قوائم بريدنا الإلكتروني في أي وقت بالنقر على رابط إلغاء الاشتراك أو الخيار المماثل المُضمَّن في كل رسالة. ولا نُرسل الرسائل الإلكترونية إلا إلى من أذن لنا بالتواصل معهم، إما مباشرةً أو عبر طرف ثالث، ولا نُرسل رسائل تجارية غير مرغوب فيها (Spam). بتقديم بريدك الإلكتروني، توافق أيضًا على السماح لنا باستخدامه لاستهداف شرائح العملاء على منصات كـ Facebook بإعلانات موجَّهة لمن اختار تلقّي مراسلاتنا. أما عناوين البريد الإلكتروني المُقدَّمة حصرًا عبر صفحة معالجة الطلبات، فلن تُستخدَم إلا لإرسال المعلومات والتحديثات المتعلقة بطلبك. غير أنه إذا قدّمت لنا البريد الإلكتروني ذاته عبر وسيلة أخرى، فقد نستخدمه لأي من الأغراض المنصوص عليها في هذه السياسة. ملاحظة: إذا رغبت في أي وقت في التوقف عن تلقّي الرسائل الإلكترونية المستقبلية، فإننا نُدرج تعليمات تفصيلية لإلغاء الاشتراك في أسفل كل رسالة.
                  `
                }}
              </p>
            </div>
            <div class="uses">
              <h3 class="condH">{{ isEnglish ? 'How Long Do We Keep Your Information?' : 'كم من الوقت نحتفظ بمعلوماتك؟' }}</h3>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  We keep your information only so long as we need it to provide Sabri Training Center to you and fulfill the purposes described in
this policy. This is also the case for anyone that we share your information with and who carries out services on our behalf. When
we no longer need to use your information and there is no need for us to keep it to comply with our legal or regulatory
obligations, we’ll either remove it from our systems or depersonalize it so that we can't identify you.

                  ` 
                  : 
                  `
                  نحتفظ بمعلوماتك طوال الفترة التي نحتاجها فيها لتقديم خدمات مركز د. صبري أبوقرون للتدريب لك وتحقيق الأغراض المبيَّنة في هذه السياسة. وينطبق الأمر ذاته على كل من نُشارك معلوماتك معه وينفّذ خدمات نيابةً عنّا. فإذا لم نعد بحاجة إلى معلوماتك ولم يكن ثمة موجب قانوني أو تنظيمي للاحتفاظ بها، فإننا نُزيلها من أنظمتنا أو نُجرّدها من أي معرّفات شخصية بحيث لا يمكن ربطها بك.
                  `
                }}
              </p>
            </div>

            <div class="uses">
              <h3 class="condH">{{ isEnglish ? 'How Do We Protect Your Information?' : 'كيف نحمي معلوماتك؟' }}</h3>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  We implement a variety of security measures to maintain the safety of your personal information when you place an order or
enter, submit, or access your personal information. We offer the use of a secure server. All supplied sensitive/credit information
is transmitted via Secure Socket Layer (SSL) technology and then encrypted into our Payment gateway providers database
only to be accessible by those authorized with special access rights to such systems, and are required to keep the information
confidential. After a transaction, your private information (credit cards, social security numbers, financials, etc.) is never kept on
file. We cannot, however, ensure or warrant the absolute security of any information you transmit to Sabri Training Center or
guarantee that your information on the Service may not be accessed, disclosed, altered, or destroyed by a breach of any of our
physical, technical, or managerial safeguards.
                  ` 
                  : 
                  `
                  نتّخذ جملةً من التدابير الأمنية للحفاظ على سلامة معلوماتك الشخصية عند تقديم طلب أو إدخال معلوماتك الشخصية أو رفعها أو الاطلاع عليها. ونُوفّر خوادم آمنة، إذ تُنقَل جميع البيانات الحساسة وبيانات بطاقات الائتمان المُقدَّمة عبر تقنية طبقة المقابس الآمنة (SSL) ثم تُشفَّر في قاعدة بيانات مزوّدي بوّابات الدفع لدينا، ولا يمكن الوصول إليها إلا لمن يملكون صلاحيات خاصة، مع إلزامهم بالسرية التامة. ولا تُحتفَظ بمعلوماتك الخاصة (أرقام بطاقات الائتمان والأرقام القومية والبيانات المالية وغيرها) في ملفاتنا بعد إتمام أي معاملة. غير أننا لا نستطيع ضمان الأمان المطلق لأي معلومات تُرسلها إلى مركز د. صبري أبوقرون للتدريب، أو ضمان عدم تعرّض معلوماتك على الخدمة للوصول غير المصرّح به أو الإفصاح أو التعديل أو الإتلاف جرّاء اختراق أيٍّ من ضماناتنا المادية أو التقنية أو الإدارية.
                  `
                }}
              </p>
            </div>

            <div class="uses">
              <h3 class="condH">{{ isEnglish ? 'Could my information be transferred to other countries?' : `هل يمكن نقل معلوماتي إلى دول أخرى؟` }}</h3>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  Sabri Training Center is incorporated in Sudan. Information collected via our website, through direct interactions with you, or
from use of our help services may be transferred from time to time to our offices or personnel, or to third parties, located
throughout the world, and may be viewed and hosted anywhere in the world, including countries that may not have laws of
general applicability regulating the use and transfer of such data. To the fullest extent allowed by applicable law, by using any
of the above, you voluntarily consent to the trans-border transfer and hosting of such information.
                  ` 
                  : 
                  `
                  مركز د. صبري أبوقرون للتدريب مُؤسَّس في جمهورية السودان. وقد تُنقَل المعلومات التي يجمعها موقعنا الإلكتروني أو التفاعلات المباشرة معك أو استخدام خدمات الدعم لدينا، من حين إلى آخر، إلى مكاتبنا أو موظفينا أو إلى أطراف ثالثة في أي مكان في العالم، ويجوز عرضها واستضافتها في أي دولة، بما فيها الدول التي قد لا تمتلك قوانين ذات تطبيق عام تنظّم استخدام هذه البيانات ونقلها. وبالقدر الأقصى المسموح به بموجب القانون المعمول به، فإنك بالاستفادة من أي مما ذُكر أعلاه توافق طوعًا على نقل هذه المعلومات عبر الحدود واستضافتها خارج بلدك.
                  `
                }}
              </p>
            </div>

            <div class="uses">
              <h3 class="condH">{{ isEnglish ? `Is the information collected through the Sabri Training
Center Service secure?` : `هل المعلومات المجموعة عبر خدمة مركز د. صبري أبوقرون للتدريب آمنة؟` }}</h3>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  We take precautions to protect the security of your information. We have physical, electronic, and managerial procedures to
help safeguard, prevent unauthorized access, maintain data security, and correctly use your information. However, neither
people nor security systems are foolproof, including encryption systems. In addition, people can commit intentional crimes,
make mistakes or fail to follow policies. Therefore, while we use reasonable efforts to protect your personal information, we
cannot guarantee its absolute security. If applicable law imposes any non-disclaimable duty to protect your personal
information, you agree that intentional misconduct will be the standards used to measure our compliance with that duty.

                  ` 
                  : 
                  `
                  نتّخذ الاحتياطات اللازمة لحماية أمن معلوماتك، ولدينا إجراءات مادية وإلكترونية وإدارية تُساعد على الحماية ومنع الوصول غير المصرّح به والحفاظ على أمان البيانات واستخدام معلوماتك على النحو الصحيح. غير أنه لا البشر ولا أنظمة الأمان، بما فيها أنظمة التشفير، خالية من الثغرات. فضلًا عن ذلك، قد يرتكب البشر جرائم متعمّدة أو أخطاء أو قد يُخفقون في الالتزام بالسياسات. ولهذا، وبينما نبذل جهودًا معقولة لحماية معلوماتك الشخصية، لا نستطيع ضمان أمانها المطلق. وإذا أوجب القانون المعمول به واجبًا لا يمكن إخلاء المسؤولية منه لحماية معلوماتك الشخصية، فإنك توافق على أن معيار الإخلال المتعمد هو المعيار المعتمد لقياس مدى امتثالنا لهذا الواجب.
                  `
                }}
              </p>
            </div>

            <div class="uses">
              <h3 class="condH">{{ isEnglish ? `Can I update or correct my information?` : `هل يمكنني تحديث أو تصحيح معلوماتي؟` }}</h3>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  The rights you have to request updates or corrections to the information Sabri Training Center collects depend on your
relationship with Sabri Training Center. Personnel may update or correct their information as detailed in our internal company
employment policies.

                  ` 
                  : 
                  `
                  تتوقف الحقوق المتاحة لك في طلب تحديث المعلومات التي يجمعها مركز د. صبري أبوقرون للتدريب أو تصحيحها على طبيعة علاقتك به. أما الموظفون فيجوز لهم تحديث معلوماتهم أو تصحيحها وفق ما تُحدّده سياسات التوظيف الداخلية للشركة.
                  `
                }}
              </p>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  Customers have the right to request the restriction of certain uses and disclosures of personally identifiable information as
follows. You can contact us in order to (1) update or correct your personally identifiable information, (2) change your
preferences with respect to communications and other information you receive from us, or (3) delete the personally identifiable
information maintained about you on our systems (subject to the following paragraph), by cancelling your account. Such
updates, corrections, changes and deletions will have no effect on other information that we maintain, or information that we
have provided to third parties in accordance with this Privacy Policy prior to such update, correction, change or deletion. To
protect your privacy and security, we may take reasonable steps (such as requesting a unique password) to verify your identity
before granting you profile access or making corrections. You are responsible for maintaining the secrecy of your unique
password and account information at all times.
                  ` 
                  : 
                  `
                  يحق للعملاء طلب تقييد استخدامات معينة للمعلومات الشخصية التعريفية والإفصاح عنها. ويمكنك التواصل معنا من أجل: (1) تحديث معلوماتك الشخصية التعريفية أو تصحيحها، (2) تعديل تفضيلاتك بشأن المراسلات وسائر المعلومات التي تتلقاها منّا، أو (3) حذف المعلومات الشخصية التعريفية المحفوظة عنك في أنظمتنا (وفقًا للفقرة التالية) عن طريق إلغاء حسابك. ولن تؤثر هذه التحديثات والتصحيحات والتغييرات والحذوفات على المعلومات الأخرى التي نحتفظ بها، ولا على المعلومات التي قدّمناها إلى أطراف ثالثة وفق سياسة الخصوصية هذه قبل إجراء هذه التعديلات. وحمايةً لخصوصيتك وأمانك، قد نتّخذ خطوات معقولة للتحقق من هويتك (كطلب كلمة مرور مخصصة) قبل منحك صلاحية الوصول إلى ملفك الشخصي أو إجراء أي تصحيحات. وأنت مسؤول مسؤوليةً كاملة عن الحفاظ على سرية كلمة مرورك ومعلومات حسابك في جميع الأوقات.
                  `
                }}
              </p>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  You should be aware that it is not technologically possible to remove each and every record of the information you have
provided to us from our system. The need to back up our systems to protect information from inadvertent loss means that a
copy of your information may exist in a non-erasable form that will be difficult or impossible for us to locate. Promptly after
receiving your request, all personal information stored in databases we actively use, and other readily searchable media will be
updated, corrected, changed or deleted, as appropriate, as soon as and to the extent reasonably and technically practicable.

                  ` 
                  : 
                  `
                  ينبغي أن تعلم أنه لا يمكن تقنيًا إزالة كل سجل للمعلومات التي قدّمتها لنا من نظامنا. فاحتياجنا إلى النسخ الاحتياطي لأنظمتنا لحماية المعلومات من الضياع غير المقصود يعني أن نسخةً من معلوماتك قد توجد في صيغة غير قابلة للمسح يتعذّر علينا تحديد موقعها أو يستحيل. وفور تلقّي طلبك، سيُحدَّث أو يُصحَّح أو يُغيَّر أو يُحذَف كل ما هو مخزَّن من معلوماتك الشخصية في قواعد البيانات التي نستخدمها فعليًا وغيرها من الوسائط سهلة البحث، على النحو المناسب، وفي أقرب وقت ممكن وبالقدر المعقول عمليًا.
                  `
                }}
              </p>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  If you are an end user and wish to update, delete, or receive any information we have about you, you may do so by contacting
the organization of which you are a customer.

                  `
                  :
                  `
                  إذا كنت مستخدمًا نهائيًا وترغب في تحديث أي معلومات نحتفظ بها عنك أو حذفها أو الاطلاع عليها، فيمكنك القيام بذلك بالتواصل مع الجهة التي تتعامل معها بوصفك عميلًا.
                  `
                }}
              </p>
            </div>

            <div class="uses">
              <h3 class="condH">{{ isEnglish ? 'Personnel' : 'شؤون الموظفين' }}</h3>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  If you are a Sabri Training Center worker or applicant, we collect information you voluntarily provide to us. We use the
information collected for Human Resources purposes in order to administer benefits to workers and screen applicants.

                  ` 
                  : 
                  `
                  إذا كنت موظفًا أو مرشّحًا للتوظيف في مركز د. صبري أبوقرون للتدريب، فإننا نجمع المعلومات التي تُقدّمها لنا طوعًا، ونستخدمها لأغراض الموارد البشرية لإدارة مزايا الموظفين وتقييم المرشّحين.
                  `
                }}
              </p>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  You may contact us in order to (1) update or correct your information, (2) change your preferences with respect to
communications and other information you receive from us, or (3) receive a record of the information we have relating to you.
Such updates, corrections, changes and deletions will have no effect on other information that we maintain, or information that
we have provided to third parties in accordance with this Privacy Policy prior to such update, correction, change or deletion.

                  ` 
                  : 
                  `
                  يمكنك التواصل معنا من أجل: (1) تحديث معلوماتك أو تصحيحها، (2) تعديل تفضيلاتك بشأن المراسلات وسائر المعلومات التي تتلقاها منّا، أو (3) الحصول على سجل بالمعلومات التي نحتفظ بها عنك. ولن تؤثر هذه التحديثات والتصحيحات والتغييرات والحذوفات على المعلومات الأخرى التي نحتفظ بها، ولا على المعلومات التي قدّمناها إلى أطراف ثالثة وفق سياسة الخصوصية هذه قبل إجراء هذه التعديلات.
                  `
                }}
              </p>
            </div>

            <div class="uses">
              <h3 class="condH">{{ isEnglish ? 'Sale of Business' : 'بيع المنشأة' }}</h3>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  We reserve the right to transfer information to a third party in the event of a sale, merger or other transfer of all or substantially
all of the assets of Sabri Training Center or any of its Corporate Affiliates (as defined herein), or that portion of Sabri Training
Center or any of its Corporate Affiliates to which the Service relates, or in the event that we discontinue our business or file a
petition or have filed against us a petition in bankruptcy, reorganization or similar proceeding, provided that the third party
agrees to adhere to the terms of this Privacy Policy.

                  ` 
                  : 
                  `
                  نحتفظ بالحق في نقل المعلومات إلى طرف ثالث في حالة بيع أصول مركز د. صبري أبوقرون للتدريب أو أيٍّ من شركاته التابعة (كما هو مُعرَّف هنا) كليًّا أو جوهريًّا أو جزء منها المتعلق بالخدمة، سواء تمّ ذلك عبر عملية بيع أو اندماج أو نقل من أي نوع، وكذلك في حال توقفنا عن ممارسة أعمالنا أو تقدّمنا بطلب إفلاس أو صدور حكم بإفلاسنا أو إعادة هيكلتنا أو ما شابه ذلك من إجراءات، وذلك شريطة أن يوافق الطرف الثالث على الالتزام ببنود سياسة الخصوصية هذه.
                  `
                }}
              </p>
            </div>
            <div class="uses">
              <h3 class="condH">{{ isEnglish ? 'Affiliates' : 'الشركات التابعة' }}</h3>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  We may disclose information (including personal information) about you to our Corporate Affiliates. For purposes of this Privacy
Policy, "Corporate Affiliate" means any person or entity which directly or indirectly controls, is controlled by or is under common
control with Sabri Training Center, whether by ownership or otherwise. Any information relating to you that we provide to our
Corporate Affiliates will be treated by those Corporate Affiliates in accordance with the terms of this Privacy Policy.
                  ` 
                  : 
                  `
                  قد نُفصح عن معلومات تخصّك (بما فيها المعلومات الشخصية) إلى شركاتنا التابعة. ولأغراض هذه السياسة، تعني «الشركة التابعة» أي شخص طبيعي أو اعتباري يتحكم بصورة مباشرة أو غير مباشرة في مركز د. صبري أبوقرون للتدريب، أو يخضع لسيطرته، أو يخضع معه لسيطرة مشتركة، سواء عبر الملكية أو بأي طريقة أخرى. وتتولى الشركات التابعة التعامل مع أي معلومات تخصّك نُقدّمها إليها وفق بنود سياسة الخصوصية هذه.
                  `
                }}
              </p>
            </div>
            <div class="uses">
              <h3 class="condH">{{ isEnglish ? 'Governing Law' : 'القانون الواجب التطبيق' }}</h3>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  This Privacy Policy is governed by the laws of Sudan without regard to its conflict of laws provision. You consent to the
exclusive jurisdiction of the courts in connection with any action or dispute arising between the parties under or in connection
with this Privacy Policy except for those individuals who may have rights to make claims under Privacy Shield, or the Swiss-US
framework.

                  ` 
                  : 
                  `
                  تخضع سياسة الخصوصية هذه لأحكام القانون السوداني بصرف النظر عن قواعد تنازع القوانين. وتوافق على الاختصاص القضائي الحصري للمحاكم السودانية فيما يخصّ أي دعوى أو نزاع ينشأ بين الأطراف بموجب هذه السياسة أو يتعلق بها، باستثناء الأفراد الذين قد يكون لهم حق تقديم مطالبات بموجب درع الخصوصية (Privacy Shield) أو الإطار السويسري-الأمريكي.
                  `
                }}
              </p>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  The laws of Sudan, excluding its conflicts of law rules, shall govern this Agreement and your use of the website. Your use of the
website may also be subject to other local, state, national, or international laws.

                  ` 
                  : 
                  `
                  تحكم قوانين السودان هذه الاتفاقية واستخدامك للموقع الإلكتروني، مع استبعاد قواعد تنازع القوانين. وقد يخضع استخدامك للموقع كذلك لقوانين محلية أو وطنية أو إقليمية أو دولية أخرى.
                  `
                }}
              </p>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  By using Sabri Training Center or contacting us directly, you signify your acceptance of this Privacy Policy. If you do not agree
to this Privacy Policy, you should not engage with our website, or use our services. Continued use of the website, direct
engagement with us, or following the posting of changes to this Privacy Policy that do not significantly affect the use or
disclosure of your personal information will mean that you accept those changes.
                  ` 
                  : 
                  `
                  باستخدامك مركز د. صبري أبوقرون للتدريب أو تواصلك معنا مباشرةً، فإنك تُقرّ بموافقتك على سياسة الخصوصية هذه. وإن كنت لا توافق على هذه السياسة، فيجب ألا تتعامل مع موقعنا الإلكتروني أو تستخدم خدماتنا. ويُعدّ استمرارك في استخدام الموقع أو التعامل المباشر معنا أو الاطلاع على التعديلات التي تُجرى على هذه السياسة دون اعتراض قبولًا منك لتلك التعديلات، ما لم تكن تلك التعديلات تؤثر تأثيرًا جوهريًا على استخدام معلوماتك الشخصية أو الإفصاح عنها.
                  `
                }}
              </p>
            </div>

            <div class="uses">
              <h3 class="condH">{{ isEnglish ? 'Your Consent' : 'موافقتك' }}</h3>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  We've updated our Privacy Policy to provide you with complete transparency into what is being set when you visit our site and
how it's being used. By using our Sabri Training Center, registering an account, or making a purchase, you hereby consent to our
Privacy Policy and agree to its terms.

                  ` 
                  : 
                  `
                  حدّثنا سياسة الخصوصية لدينا لنوفّر لك شفافية كاملة حول ما يُعيَّن عند زيارتك موقعنا وكيفية استخدامه. باستخدامك مركز د. صبري أبوقرون للتدريب، أو تسجيلك حسابًا، أو إجرائك عملية شراء، فإنك بذلك تمنح موافقتك على سياسة الخصوصية هذه وتوافق على شروطها.
                  `
                }}
              </p>
            </div>
            <div class="uses">
              <h3 class="condH">{{ isEnglish ? `Links to Other Websites
` : `روابط إلى مواقع أخرى` }}</h3>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  This Privacy Policy applies only to the Services. The Services may contain links to other websites not operated or controlled
by Sabri Training Center. We are not responsible for the content, accuracy or opinions expressed in such websites, and such
websites are not investigated, monitored or checked for accuracy or completeness by us. Please remember that when you use
a link to go from the Services to another website, our Privacy Policy is no longer in effect. Your browsing and interaction on any
other website, including those that have a link on our platform, is subject to that website’s own rules and policies. Such third
parties may use their own cookies or other methods to collect information about you.

                  ` 
                  : 
                  `
                  تسري سياسة الخصوصية هذه على خدماتنا فحسب. وقد تتضمن خدماتنا روابط إلى مواقع أخرى لا تديرها أو تتحكم فيها مركز د. صبري أبوقرون للتدريب. ولا نتحمل أي مسؤولية عن محتوى تلك المواقع أو دقتها أو الآراء المعبَّر عنها فيها، كما أننا لا نخضعها للفحص أو المراقبة أو التحقق من دقتها أو اكتمالها. يُرجى التنبّه إلى أن سياسة الخصوصية لدينا تُصبح غير سارية فور انتقالك عبر أي رابط من خدماتنا إلى موقع آخر، إذ يخضع تصفّحك وتفاعلك على أي موقع آخر — بما فيها المواقع التي تحمل روابط على منصتنا — للقواعد والسياسات الخاصة بتلك المواقع. وقد تستخدم تلك الأطراف الثالثة ملفات تعريف الارتباط الخاصة بها أو وسائل أخرى لجمع معلومات عنك.
                  `
                }}
              </p>
            </div>

            <div class="uses">
              <h3 class="condH">{{ isEnglish ? 'Cookies' : 'ملفات تعريف الارتباط' }}</h3>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  Sabri Training Center uses "Cookies" to identify the areas of our website that you have visited. A Cookie is a small piece of data
stored on your computer or mobile device by your web browser. We use Cookies to enhance the performance and functionality
of our website but are non-essential to their use. However, without these cookies, certain functionality like videos may become
unavailable or you would be required to enter your login details every time you visit the website as we would not be able to
remember that you had logged in previously. Most web browsers can be set to disable the use of Cookies. However, if you
disable Cookies, you may not be able to access functionality on our website correctly or at all. We never place Personally
Identifiable Information in Cookies.

                  ` 
                  :
                  `
                  يستخدم مركز د. صبري أبوقرون للتدريب ملفات تعريف الارتباط (Cookies) لتحديد صفحات موقعنا التي قمت بزيارتها. وملف تعريف الارتباط هو جزء صغير من البيانات يُخزَّن على حاسوبك أو جهازك المحمول بواسطة متصفحك. نستخدم هذه الملفات لتحسين أداء موقعنا ووظائفه، وإن كانت غير ضرورية لاستخدام الخدمة. غير أنه في غياب هذه الملفات، قد تتوقف بعض الوظائف كمشغّل الفيديو عن العمل، أو قد تُطالَب بإدخال بيانات تسجيل الدخول في كل زيارة لعدم قدرتنا على تذكّر جلساتك السابقة. ويمكن ضبط معظم المتصفحات لتعطيل ملفات تعريف الارتباط، غير أن ذلك قد يحول دون وصولك الكامل إلى وظائف موقعنا أو يُعطّله كليًّا. ولا نُخزّن في ملفات تعريف الارتباط قطّ أي معلومات شخصية تعريفية.
                  `
                }}
              </p>
            </div>
            <div class="uses">
              <h3 class="condH">{{ isEnglish ? `Blocking and disabling cookies and similar
technologies` : `حظر ملفات تعريف الارتباط والتقنيات المماثلة وتعطيلها` }}</h3>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  Wherever you're located you may also set your browser to block cookies and similar technologies, but this action may block our
essential cookies and prevent our website from functioning properly, and you may not be able to fully utilize all of its features
and services. You should also be aware that you may also lose some saved information (e.g. saved login details, site
preferences) if you block cookies on your browser. Different browsers make different controls available to you. Disabling a
cookie or category of cookie does not delete the cookie from your browser, you will need to do this yourself from within your
browser, you should visit your browser's help menu for more information.
                  ` 
                  : 
                  `
                  أيًّا كان موقعك، يمكنك ضبط متصفحك لحظر ملفات تعريف الارتباط والتقنيات المماثلة، إلا أن ذلك قد يُعطّل ملفات تعريف الارتباط الأساسية ويمنع موقعنا من العمل بصورة صحيحة، فلا تتمكن من الاستفادة الكاملة من جميع ميزاته وخدماته. كما ينبغي أن تعلم أن حظر ملفات تعريف الارتباط قد يُفضي إلى فقدان بعض المعلومات المحفوظة لديك (كبيانات تسجيل الدخول المحفوظة وتفضيلات الموقع). وتتفاوت أدوات التحكم المتاحة من متصفح إلى آخر. ولا يؤدي تعطيل ملف تعريف الارتباط أو فئة منها إلى حذفه من متصفحك؛ بل يتعيّن عليك حذفه يدويًا من داخل المتصفح، ويُنصح بمراجعة قائمة المساعدة في متصفحك للاستفسار عن كيفية ذلك.
                  `
                }}
              </p>
            </div>

            <div class="uses">
              <h3 class="condH">{{ isEnglish ? 'Payment Details' : 'بيانات الدفع' }}</h3>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  In respect to any credit card or other payment processing details you have provided us, we commit that this confidential
information will be stored in the most secure manner possible.

                  ` 
                  : 
                  `
                  فيما يخصّ أي بيانات تتعلق ببطاقة الائتمان أو وسائل الدفع الأخرى التي قدّمتها لنا، نُقرّ بأن هذه المعلومات السرية ستُخزَّن بأعلى معايير الأمان الممكنة.
                  `
                }}
              </p>
            </div>

            <div class="uses">
              <h3 class="condH">{{ isEnglish ? `Kids' Privacy` : `خصوصية الأطفال` }}</h3>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  We collect information from kids under the age of 13 just to better our services. If You are a parent or guardian and You are
aware that Your child has provided Us with Personal Data without your permission, please contact Us. If We become aware that
We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to
remove that information from Our servers.
                  ` 
                  : 
                  `
                  لا نجمع معلومات من الأطفال دون سن الثالثة عشرة إلا بالقدر اللازم لتحسين خدماتنا. إذا كنت وليًّا أو وصيًّا وعلمت أن طفلك قد زوّدنا ببيانات شخصية دون إذنك، فيُرجى التواصل معنا فورًا. وإذا تبيّن لنا أننا جمعنا بيانات شخصية من أي شخص دون سن الثالثة عشرة دون التحقق من موافقة وليّ الأمر، فإننا نتّخذ الخطوات اللازمة لحذف تلك المعلومات من خوادمنا.
                  `
                }}
              </p>
            </div>

            <div class="uses">
              <h3 class="condH">{{ isEnglish ? `Changes To Our Privacy Policy
` : `التعديلات على سياسة الخصوصية` }}</h3>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  We may change our Service and policies, and we may need to make changes to this Privacy Policy so that they accurately
reflect our Service and policies. Unless otherwise required by law, we will notify you (for example, through our Service) before
we make changes to this Privacy Policy and give you an opportunity to review them before they go into effect. Then, if you
continue to use the Service, you will be bound by the updated Privacy Policy. If you do not want to agree to this or any updated
Privacy Policy, you can delete your account.
                  ` 
                  : 
                  `
                  قد نُعدّل خدمتنا وسياساتنا، وقد يستلزم ذلك إجراء تغييرات على سياسة الخصوصية هذه لتعكس بدقة ما استجدّ من خدمات وسياسات. وما لم يوجب القانون خلاف ذلك، سنُخطرك (عبر خدمتنا مثلًا) قبل إجراء أي تغييرات على هذه السياسة ونمنحك فرصةً لمراجعتها قبل نفاذها. وإذا واصلت استخدام الخدمة بعد ذلك، فستكون ملزمًا بسياسة الخصوصية المحدَّثة. وإن كنت لا ترغب في الموافقة على هذه السياسة أو أي تحديث مستقبلي لها، فبإمكانك حذف حسابك.
                  `
                }}
              </p>
            </div>

            <div class="uses">
              <h3 class="condH">{{ isEnglish ? 'Third-Party Services' : 'خدمات الأطراف الثالثة' }}</h3>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  We may display, include or make available third-party content (including data, information, applications and other products
services) or provide links to third-party websites or services ("Third- Party Services").
                  ` 
                  : 
                  `
                  قد نعرض محتوى أطراف ثالثة أو نُدرجه أو نُتيحه (بما في ذلك البيانات والمعلومات والتطبيقات والمنتجات والخدمات الأخرى)، أو نُوفّر روابط إلى مواقع أو خدمات تلك الأطراف (يُشار إليها بـ«خدمات الأطراف الثالثة»).
                  `
                }}
              </p>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  You acknowledge and agree that Sabri Training Center shall not be responsible for any Third-Party Services, including their
accuracy, completeness, timeliness, validity, copyright compliance, legality, decency, quality or any other aspect thereof. Sabri
Training Center does not assume and shall not have any liability or responsibility to you or any other person or entity for any
Third-Party Services.

                  ` 
                  :
                  `
                  تُقرّ وتوافق على أن مركز د. صبري أبوقرون للتدريب لن يكون مسؤولًا عن أي خدمات تقدّمها أطراف ثالثة، بما في ذلك دقتها واكتمالها وتوقيتها وصلاحيتها ومدى امتثالها لحقوق الملكية الفكرية وقانونيّتها وملاءمتها وجودتها وأي جانب آخر منها. ولا يتحمّل مركز د. صبري أبوقرون للتدريب أي التزام أو مسؤولية تجاهك أو تجاه أي شخص أو جهة أخرى فيما يخصّ خدمات الأطراف الثالثة.
                  `
                }}
              </p>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  Third-Party Services and links thereto are provided solely as a convenience to you and you access and use them entirely at your
own risk and subject to such third parties' terms and conditions.

                  ` 
                  : 
                  `
                  تُوفَّر خدمات الأطراف الثالثة والروابط المؤدية إليها لأغراض ملاءمتك فحسب، ويعود إليك وحدك تحمّل كامل المسؤولية عن الوصول إليها واستخدامها، وذلك وفق الشروط والأحكام الخاصة بكل طرف ثالث.
                  `
                }}
              </p>
            </div>

            <div class="uses">
              <h3 class="condH">{{ isEnglish ? `Tracking Technologies
` : `تقنيات التتبع` }}</h3>
              <p class="condP">
                {{ 
                  isEnglish
                  ?
                  `
                  * Local Storage
                  ` 
                  : 
                  `
                  * التخزين المحلي
                  `
                }}
              </p>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  Local Storage sometimes known as DOM storage, provides web apps with methods and protocols for storing client-side
data. Web storage supports persistent data storage, similar to cookies but with a greatly enhanced capacity and no
information stored in the HTTP request header.
                  ` 
                  : 
                  `
                  التخزين المحلي، المعروف أحيانًا بتخزين DOM، يُوفّر لتطبيقات الويب أساليب وبروتوكولات لتخزين البيانات على جانب المستخدم (Client-side). ويدعم التخزين على الويب حفظ البيانات بصورة مستمرة، على غرار ملفات تعريف الارتباط، غير أنه يتمتع بسعة تخزينية أكبر بكثير ولا يتضمّن المعلومات في رأس طلبات HTTP.
                  `
                }}
              </p>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  * Sessions
                  `
                  :
                  `
                  * جلسات الاتصال (Sessions)
                  `
                }}
              </p>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  uses "Sessions" to identify the areas of our website that you have visited. A Session is a small piece of data stored on
your computer or mobile device by your web browser.

                  ` 
                  :
                  `
                  نستخدم «جلسات الاتصال» لتحديد الصفحات التي زرتها على موقعنا. والجلسة هي جزء صغير من البيانات يُخزَّن على حاسوبك أو جهازك المحمول عبر متصفحك.
                  `
                }}
              </p>
            </div>
            <div class="uses">
              <h3 class="condH">{{ isEnglish ? `Information about General Data Protection Regulation
(GDPR)
` : `معلومات حول اللائحة العامة لحماية البيانات (GDPR)` }}</h3>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  We may be collecting and using information from you if you are from the European Economic Area (EEA), and in this section of
our Privacy Policy we are going to explain exactly how and why is this data collected, and how we maintain this data under
protection from being replicated or used in the wrong way.
                  ` 
                  : 
                  `
                  إذا كنت مقيمًا في المنطقة الاقتصادية الأوروبية (EEA)، فقد نجمع معلومات منك ونستخدمها. وفي هذا القسم من سياسة الخصوصية لدينا، سنوضّح بدقة كيف تُجمَع هذه البيانات ولماذا، وكيف نصون حمايتها من إعادة استخدامها أو توظيفها على نحو غير ملائم.
                  `
                }}
              </p>
            </div>

            <div class="uses">
              <h3 class="condH">{{ isEnglish ? `What is GDPR?` : `ما هي اللائحة العامة لحماية البيانات (GDPR)؟` }}</h3>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  GDPR is an EU-wide privacy and data protection law that regulates how EU residents' data is protected by companies and
enhances the control the EU residents have, over their personal data.

                  ` 
                  : 
                  `
                  اللائحة العامة لحماية البيانات (GDPR) هي تشريع خاص بحماية الخصوصية والبيانات يسري على مستوى الاتحاد الأوروبي، وينظّم الكيفية التي تحمي بها الشركات بيانات المقيمين في الاتحاد الأوروبي، ويُعزّز سيطرتهم على بياناتهم الشخصية.
                  `
                }}
              </p>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  The GDPR is relevant to any globally operating company and not just the EU-based businesses and EU residents. Our
customers’ data is important irrespective of where they are located, which is why we have implemented GDPR controls as our
baseline standard for all our operations worldwide.
                  ` 
                  : 
                  `
                  تسري اللائحة العامة لحماية البيانات على أي شركة تعمل على المستوى العالمي، ولا تقتصر على الشركات المقيمة في الاتحاد الأوروبي أو المتعامِلة مع مقيميه. وتُعدّ بيانات عملائنا مسؤوليةً أساسية بصرف النظر عن موقعهم الجغرافي، ولذا اعتمدنا ضوابط اللائحة العامة لحماية البيانات معيارًا أساسيًا لجميع عملياتنا في مختلف أنحاء العالم.
                  `
                }}
              </p>
            </div>

            <div class="uses">
              <h3 class="condH">{{ isEnglish ? `What is personal data?` : `ما المقصود بالبيانات الشخصية؟` }}</h3>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  Any data that relates to an identifiable or identified individual. GDPR covers a broad spectrum of information that could be used
on its own, or in combination with other pieces of information, to identify a person. Personal data extends beyond a person’s
name or email address. Some examples include financial information, political opinions, genetic data, biometric data, IP
addresses, physical address, sexual orientation, and ethnicity.
                  ` 
                  : 
                  `
                  هي أي بيانات تتعلق بفرد محدد الهوية أو يمكن تحديد هويته. وتشمل اللائحة العامة لحماية البيانات طيفًا واسعًا من المعلومات التي يمكن استخدامها بمفردها أو بالاقتران مع معلومات أخرى لتعريف شخص ما. والبيانات الشخصية أوسع من مجرد الاسم أو عنوان البريد الإلكتروني، وتشمل على سبيل المثال: المعلومات المالية، والآراء السياسية، والبيانات الجينية، والبيانات البيومترية، وعناوين IP، والعنوان المادي، والتوجه الجنسي، والانتماء العرقي.
                  `
                }}
              </p>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  The Data Protection Principles include requirements such as:
                  ` 
                  : 
                  `
                  تتضمّن مبادئ حماية البيانات متطلبات من بينها:
                  `
                }}
              </p>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  * Personal data collected must be processed in a fair, legal, and transparent way and should only be used in a way that a
person would reasonably expect.
                  
                  ` 
                  : 
                  `
                  * يجب معالجة البيانات الشخصية المجموعة بطريقة منصفة وقانونية وشفافة، ولا يجوز استخدامها إلا بالأسلوب الذي يتوقعه صاحبها بصورة معقولة.
                  `
                }}
              </p>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  * Personal data should only be collected to fulfil a specific purpose and it should only be used for that purpose.
Organizations must specify why they need the personal data when they collect it.
                  ` 
                  : 
                  `
                  * لا يجوز جمع البيانات الشخصية إلا لتحقيق غرض محدد، ولا يجوز استخدامها لغير ذلك الغرض. ويجب على الجهات أن تُحدّد، عند الجمع، الأسباب التي تدعوها إلى الحاجة لهذه البيانات.
                  `
                }}
              </p>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  * Personal data should be held no longer than necessary to fulfil its purpose.
                  ` 
                  : 
                  `
                  * لا يجوز الاحتفاظ بالبيانات الشخصية لمدة تتجاوز ما هو ضروري لتحقيق الغرض المنشود منها.
                  `
                }}
              </p>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  * People covered by the GDPR have the right to access their own personal data. They can also request a copy of their
data, and that their data be updated, deleted, restricted, or moved to another organization.
                  ` 
                  : 
                  `
                  * يحق للأشخاص المشمولين باللائحة العامة لحماية البيانات الاطلاع على بياناتهم الشخصية، كما يحق لهم طلب نسخة منها، وطلب تحديثها أو حذفها أو تقييد معالجتها أو نقلها إلى جهة أخرى.
                  `
                }}
              </p>
            </div>

            <div class="uses">
              <h3 class="condH">{{ isEnglish ? `Why is GDPR important?` : `لماذا تُعدّ اللائحة العامة لحماية البيانات (GDPR) مهمة؟` }}</h3>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  GDPR adds some new requirements regarding how companies should protect individuals' personal data that they collect and
process. It also raises the stakes for compliance by increasing enforcement and imposing greater fines for breach. Beyond
these facts it's simply the right thing to do. At Sabri Training Center we strongly believe that your data privacy is very important
and we already have solid security and privacy practices in place that go beyond the requirements of this new regulation.

                  ` 
                  : 
                  `
                  تُضيف اللائحة العامة لحماية البيانات متطلبات جديدة تتعلق بكيفية حماية الشركات للبيانات الشخصية التي تجمعها وتعالجها. كما ترفع مستوى الامتثال من خلال تعزيز آليات التطبيق وفرض غرامات أشد على المخالفات. وبمعزل عن ذلك كله، فإن احترام خصوصية البيانات هو ببساطة الموقف الأخلاقي الصحيح. وفي مركز د. صبري أبوقرون للتدريب، نؤمن إيمانًا راسخًا بأن خصوصية بياناتك أمر بالغ الأهمية، ولدينا مسبقًا ممارسات أمنية وخصوصية متينة تتجاوز متطلبات هذه اللائحة.
                  `
                }}
              </p>
            </div>

            <div class="uses">
              <h3 class="condH">{{ isEnglish ? `Individual Data Subject's Rights - Data Access,
Portability and Deletion` : `حقوق صاحب البيانات: الوصول والنقل والحذف` }}</h3>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  We are committed to helping our customers meet the data subject rights requirements of GDPR. Sabri Training Center
processes or stores all personal data in fully vetted, DPA compliant vendors. We do store all conversation and personal data for
up to 6 years unless your account is deleted. In which case, we dispose of all data in accordance with our Terms of Service and
Privacy Policy, but we will not hold it longer than 60 days.
                  ` 
                  : 
                  `
                  نحن ملتزمون بمساعدة عملائنا في الوفاء بمتطلبات حقوق أصحاب البيانات المنصوص عليها في اللائحة العامة لحماية البيانات. ويعالج مركز د. صبري أبوقرون للتدريب جميع البيانات الشخصية ويُخزّنها لدى مزوّدين خضعوا لفحص دقيق وهم ملتزمون باتفاقيات معالجة البيانات (DPA). ونحتفظ بجميع بيانات المحادثات والبيانات الشخصية لمدة تصل إلى 6 سنوات، ما لم يُحذَف حسابك؛ وفي تلك الحالة نتصرّف في جميع البيانات وفق شروط الخدمة وسياسة الخصوصية، ولن نحتفظ بها أكثر من 60 يومًا.
                  `
                }}
              </p>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  We are aware that if you are working with EU customers, you need to be able to provide them with the ability to access, update,
retrieve and remove personal data. We got you! We've been set up as self service from the start and have always given you
access to your data and your customers data. Our customer support team is here for you to answer any questions you might
have about working with the API.

                  ` 
                  : 
                  `
                  ندرك أنك إذا كنت تتعامل مع عملاء من الاتحاد الأوروبي، فأنت بحاجة إلى منحهم إمكانية الوصول إلى بياناتهم الشخصية وتحديثها واسترجاعها وحذفها. نحن هنا لمساعدتك! فقد صُمِّمت منصّتنا منذ البداية كخدمة ذاتية، ومنحناك دائمًا صلاحية الوصول الكامل إلى بياناتك وبيانات عملائك. وفريق دعم العملاء لدينا جاهز للإجابة على أي تساؤلات تتعلق بالتعامل مع واجهة برمجة التطبيقات (API).
                  `
                }}
              </p>
            </div>

            <div class="uses">
              <h3 class="condH">{{ isEnglish ? `Contact Us` : `تواصل معنا` }}</h3>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  Don't hesitate to contact us if you have any questions.

                  ` 
                  : 
                  `
                  لا تتردد في التواصل معنا إذا كانت لديك أي استفسارات.
                  `
                }}
              </p>
              <p class="condP">
                {{ 
                  isEnglish
                  ? 
                  `
                  * Via Phone Number: +249907249203
                  ` 
                  : 
                  `
                  * عبر الهاتف: 249907249203+
                  `
                }}
              </p>
            </div>

    </section>
  </main>
</template>

<script setup lang="ts">
import { storeToRefs } from 'pinia'
import { useSettingsStore } from 'src/stores/settings'

defineOptions({ name: 'PrivacyPolicy' })

const settings = useSettingsStore()
const { isEnglish } = storeToRefs(settings)
</script>

<style lang="scss" scoped>
.legal-page {
  background: var(--ds-surface-muted);
  min-block-size: 100vh;

  &__hero {
    background: linear-gradient(135deg, var(--ds-brand-700), var(--ds-brand-600));
    color: var(--ds-text-onBrand);
    padding: var(--ds-space-10) var(--ds-space-4);

    h1 {
      max-inline-size: 1120px;
      margin: 0 auto;
      font-family: var(--ds-font-heading);
      font-size: var(--ds-text-3xl);
      font-weight: var(--ds-weight-bold);

      @media (min-width: 900px) { font-size: var(--ds-text-4xl); }
    }
  }

  &__content {
    max-inline-size: 880px;
    margin-inline: auto;
    padding: var(--ds-space-8) var(--ds-space-3) var(--ds-space-16);
    display: flex;
    flex-direction: column;
    gap: var(--ds-space-5);

    @media (min-width: 600px) { padding-inline: var(--ds-space-4); }
  }
}

// The original template uses .Conditions and .uses section blocks with
// .condH headings and .condP paragraphs — keep those class hooks and
// style them to match the DS card look used in the Terms page.
:deep(*) {
  .Conditions,
  .uses {
    background: var(--ds-surface);
    border: 1px solid var(--ds-border);
    border-radius: var(--ds-radius-lg);
    padding: var(--ds-space-5);
    box-shadow: var(--ds-shadow-xs);
    display: flex;
    flex-direction: column;
    gap: var(--ds-space-3);
  }

  .Conditions {
    border-inline-start: 4px solid var(--ds-accent-300);
    background: var(--ds-accent-50);
    .condH { color: var(--ds-accent-600); }
  }

  .condH {
    font-family: var(--ds-font-heading);
    font-size: var(--ds-text-xl);
    font-weight: var(--ds-weight-bold);
    color: var(--ds-text);
    margin: 0;
  }

  .condP {
    font-family: var(--ds-font-body);
    font-size: var(--ds-text-md);
    line-height: var(--ds-leading-arabic);
    color: var(--ds-text);
    margin: 0;
    white-space: pre-line;
  }

  br { display: none; }

  // Legacy .title block from the original — the hero already carries
  // the page heading, so hide any residual in-body titles.
  .privacy > .title { display: none; }
}
</style>
